/*
* NombreProgra.asm
*
* Creado: 3/03/2026
* Autor : Omar Cabrera
* Descripción: Proyecto Reloj
*/
/******/
// Encabezado (Definición de Registros, Variables y Constantes)
.include "M328PDEF.inc"     // Include definitions specific to ATMega328P
.dseg
.org    SRAM_START
// VARIABLES EN SRAM (MEMORIA DE DATOS)
OVERFLOW_TMR0:			.byte 1		// CONTADOR DE DESBORDAMIENTOS DEL TIMER0 PARA LOS LEDS DE EN MEDIO (250MS)					
INDICADOR_TMR1:			.byte 1		// BANDERA QUE INDICA QUE PASO 1 MINUTO
C_UNIDAD_MINUTO:		.byte 1		// CONTADOR UNIDADES DE MINUTO (0-9)
C_DECENA_MINUTO:		.byte 1		// CONTADOR DECENAS DE MINUTO (0-5)
C_UNIDAD_HORA:			.byte 1		// CONTADOR UNIDADES DE HORA (0-9)
C_DECENA_HORA:			.byte 1		// CONTADOR DECENAS DE HORA (0-2)
DISP_U_MIN:				.byte 1		// CÓDIGO DE 7 SEGMENTOS PARA UNIDAD DE MINUTO
DISP_D_MIN:				.byte 1		// CÓDIGO DE 7 SEGMENTOS PARA DECENA DE MINUTO
DISP_U_HR:				.byte 1		// CÓDIGO DE 7 SEGMENTOS PARA UNIDAD DE HORA
DISP_D_HR:				.byte 1		// CÓDIGO DE 7 SEGMENTOS PARA DECENA DE HORA
DISP_SELEC:				.byte 1		// SELECTOR DE DÍGITO PARA MULTIPLEXADO (0-3)
MODO_ESTADO:			.byte 1		// ESTADO ACTUAL DE LA MÁQUINA (00 MOSTRAR HORA, 01 MOSTRAR FECHA, 10 CONFIGURAR HORA Y SET ALARMA, 11 CONFIGURAR FECHA)
PINC_ANTERIOR:			.byte 1		// ÚLTIMO VALOR LEÍDO DE PINC (PARA DETECCIÓN DE FLANCOS)	
INDICADOR_BOTON1:		.byte 1		// BANDERA PARA INDICAR SI BOTÓN 1 FUE PRESIONADO 
INDICADOR_BOTON2:		.byte 1		// BANDERA PARA INDICAR SI BOTÓN 2 FUE PRESIONADO 
INDICADOR_BOTON3:		.byte 1		// BANDERA PARA INDICAR SI BOTÓN 3 FUE PRESIONADO 
INDICADOR_BOTON4:		.byte 1		// BANDERA PARA INDICAR SI BOTÓN 4 FUE PRESIONADO 
INDICADOR_BOTON5:		.byte 1		// BANDERA PARA INDICAR SI BOTÓN 5 FUE PRESIONADO 
C_UNIDAD_MES:			.byte 1		// CONTADOR UNIDADES DE MES (0-9)
C_DECENA_MES:			.byte 1		// CONTADOR DECENAS DE MES (0-1)
C_UNIDAD_DIA:			.byte 1		// CONTADOR UNIDADES DE DÍA (0-9)
C_DECENA_DIA:			.byte 1		// CONTADOR DECENAS DE DÍA (0-3)
DISP_U_MES:				.byte 1		// CÓDIGO DE 7 SEGMENTOS PARA UNIDAD DE MES 
DISP_D_MES:				.byte 1		// CÓDIGO DE 7 SEGMENTOS PARA DECENA DE MES 
DISP_U_DIA:				.byte 1		// CÓDIGO DE 7 SEGMENTOS PARA UNIDAD DE DÍA
DISP_D_DIA:				.byte 1		// CÓDIGO DE 7 SEGMENTOS PARA DECENA DE DÍA
MODO_DISPLAY:			.byte 1		// MODO DE VISUALIZACIÓN (0 HORA, 1 FECHA, 2 CONF DE HORA, 3 CONF DE FECHA)
INDICADOR_CAMBIO_DIA:	.byte 1		// BANDERA QUE INDICA EL PASO DE UN DÍA 
DISP_SELEC_ESTADO3:		.byte 1		// SELECTOR DE DÍGITO EN MODO CONFIGURACIÓN DE FECHA
DISP_ESTADO3_1:			.byte 1		// VARIABLE TEMPORAL PARA CONTROLAR DISPLAY DEL DÍGITO 1 EN EL ESTADO 3
DISP_ESTADO3_2:			.byte 1		// VARIABLE TEMPORAL PARA CONTROLAR DISPLAY DEL DÍGITO 2 EN EL ESTADO 3
DISP_ESTADO3_3:			.byte 1		// VARIABLE TEMPORAL PARA CONTROLAR DISPLAY DEL DÍGITO 3 EN EL ESTADO 3
DISP_ESTADO3_4:			.byte 1		// VARIABLE TEMPORAL PARA CONTROLAR DISPLAY DEL DÍGITO 4 EN EL ESTADO 3
U_MES_ESTADO3:			.byte 1		// VALOR TEMPORAL UNIDAD DE MES EN CONFIGURACIÓN DE FECHA 
D_MES_ESTADO3:			.byte 1		// VALOR TEMPORAL DECENA DE MES EN CONFIGURACIÓN DE FECHA
U_DIA_ESTADO3:			.byte 1		// VALOR TEMPORAL UNIDAD DE DIA EN CONFIGURACIÓN DE FECHA
D_DIA_ESTADO3:			.byte 1		// VALOR TEMPORAL DECENA DE DIA EN CONFIGURACIÓN DE FECHA
DISP_SELEC_ESTADO2:		.byte 1		// SELECTOR DE DÍGITO EN MODO CONFIGURACIÓN HORA (0-3)
DISP_ESTADO2_1:			.byte 1		// VARIABLE TEMPORAL PARA CONTROLAR DISPLAY DEL DÍGITO 1 EN EL ESTADO 2
DISP_ESTADO2_2:			.byte 1		// VARIABLE TEMPORAL PARA CONTROLAR DISPLAY DEL DÍGITO 2 EN EL ESTADO 2
DISP_ESTADO2_3:			.byte 1		// VARIABLE TEMPORAL PARA CONTROLAR DISPLAY DEL DÍGITO 3 EN EL ESTADO 2
DISP_ESTADO2_4:			.byte 1		// VARIABLE TEMPORAL PARA CONTROLAR DISPLAY DEL DÍGITO 4 EN EL ESTADO 2
U_MIN_ESTADO2:			.byte 1		// VALOR TEMPORAL UNIDAD DE MINUTO EN CONFIGURACIÓN DE HORA
D_MIN_ESTADO2:			.byte 1		// VALOR TEMPORAL DECENA DE MINUTO EN CONFIGURACIÓN DE HORA
U_HR_ESTADO2:			.byte 1		// VALOR TEMPORAL UNIDAD DE HORA EN CONFIGURACIÓN DE HORA
D_HR_ESTADO2:			.byte 1		// VALOR TEMPORAL DECENA DE HORA EN CONFIGURACIÓN DE HORA
U_MIN_ALARMA:			.byte 1		// UNIDAD DE MINUTO DE LA ALARMA 
D_MIN_ALARMA:			.byte 1		// DECENA DE MINUTO DE LA ALARMA
U_HR_ALARMA:			.byte 1		// UNIDAD DE HORA DE LA ALARMA 
D_HR_ALARMA:			.byte 1		// DECENA DE HORA DE LA ALARMA 
CONTADOR_ALARMA:		.byte 1		// CONTADOR PARA TIEMPO DE SONIDO DE ALARMA (DENTRO DE ISR0)
BUZZER_ENCENDIDO:		.byte 1		// BANDERA QUE INDICA SI EL BUZER ESTÁ SONANDO 

.cseg
.org 0x0000
	JMP START						// SALTO INICIO DE PROGRAMA 						
.org PCI1addr						// NOMBRE RESERVADO PARA LA DIRECCIÓN 0x0008 ; HABILITA INTERRUPCIONES PINCHANGE EN PORTC (BOTONES)  
	JMP PINC_ISR				
.org OVF2addr						// NOMBRE RESERVADO PARA LA DIRECCIÓN 0x0016 ; HABILITA INTERRUPCIONES PARA TIMER2 (MULTIPLEXADO)
	JMP ISR_TIMER2
.org OVF1addr						// NOMBRE RESERVADO PARA LA DIRECCIÓN 0x001A ; HABILITA INTERRUPCIONES PARA TIMER 1 (MINUTOS)		
	JMP ISR_TIMER1			
.org OVF0addr						// NOMBRE RESERVADO PARA LA DIRECCIÓN 0x0020 ; HABILITA INTERRUPCIONES PARA TIMER0 (LEDS DE EN MEDIO Y ALARMA)
	JMP ISR_TIMER0
 /******/
// Configuración de la pila

START:
LDI     R16, LOW(RAMEND)
OUT     SPL, R16
LDI     R16, HIGH(RAMEND)
OUT     SPH, R16

// TABLA DE CONVERSIÓN A 7 SEGMENTOS PARA (CÁTODO COMÚN)

tabla7: .DB 0x7D, 0x48, 0x3E, 0x6E, 0x4B, 0x67, 0x73, 0x4E, 0x7F, 0x4F

/******/
// CONFIGURACIÓN DEL MICROCONTROLADOR 

SETUP:
	CLI								// SE DESHABILITA INTERRUPCIONES MIENTRAS SE CONFIGURA 
	
	// SETTING PRESCALER A 1MHZ 
	LDI R16, (1<<CLKPCE)
	STS CLKPR, R16						
	LDI R16, 0b0000_0100
	STS CLKPR, R16

	// CONFIGURACIÓN DEL TIMER0 CON DELAY DE 250 MS PARA LOS LEDS DE EN MEDIO Y CONTROL DE LA ALARMA  
	LDI R16, 0x0
	OUT TCCR0A, R16						// RELOJ MODO NORMAL 
	LDI R16, 0b0000_0101				
	OUT TCCR0B, R16						// PRESCALER 1024
	LDI R16, 0x0C						
	OUT TCNT0, R16						// VALOR INICIAL DE 12 

	// CONFIGURACIÓN DE INTERRUPCIÓN PARA TIMER0 
	LDI R16, (1<< TOIE0)				 
	STS TIMSK0, R16				 

	// CONFIGURACIÓN DEL TIMER2 CON DELAY DE 2 MS PARA MULTIPLEXADO
	LDI R16, 0x0 
	STS TCCR2A, R16						// RELOJ MODO NORMAL 
	LDI R16, 0b0000_0010
	STS TCCR2B, R16						// PRESCALER DE 8
	LDI R16, 0x06 
	STS TCNT2, R16						// VALOR INICIAL DE 6 

	// CONFIGURACIÓN DE INTERRUPCIÓN PARA TIMER2 
	LDI R16, (1<< TOIE2)
	STS TIMSK2, R16						

	// CONFIGURACIÓN DEL TIMER1 CON DELAY DE 60 SEGUNDOS PARA RELOJ 
	LDI R16, 0x0 
	STS TCCR1A, R16						// RELOJ MODO NORMAL				
	LDI R16, 0b0000_0101
	STS TCCR1B, R16						// PRESCALER DE 1024 
	LDI R16, 0x1B							
	STS TCNT1H, R16						// CARGA AL BYTE ALTO: 1B
	LDI R16, 0x1F		  
	STS TCNT1L, R16						// CARGA AL BYTE BAJO: 1F PARA HACER UN TOTAL DE 6943 

	// CONFIGURACIÓN DE INTERRUPCIÓN PARA TIMER 1 
	LDI R16, (1<< TOIE1)
	STS TIMSK1, R16					

	// CONFIGURACIÓNDE INTERRUPCIÓN POR CAMBIO DE PIN EN PORTC (BOTONES)
	LDI R16, (1 << PCIE1)
	STS PCICR, R16 
	LDI R16, (1 << PCINT12)| (1 << PCINT11)| (1 << PCINT10)| (1 << PCINT9)| (1 << PCINT8)
	STS PCMSK1, R16 
	
	// CARGA DE PRIMER VALOR DE LA TABLA EN PORTD 
	LDI ZH, HIGH(tabla7<<1)
	LDI ZL, LOW(tabla7<<1)
	LPM R17, Z				 
	OUT PORTD, R17

	// CONFIGURACIÓN DE ENTRADAS Y SALIDAS 

	// CONFIGURACIÓN DE SALIDAS PARA LOS SEGMENTOS DE LOS DISPLAYS DEL PUERTO D Y EL BUZZER
	LDI R16, 0b1111_1111
	OUT DDRD, R16 
	LDI R16, 0b0000_0000 
	OUT PORTD, R16

	//CONFIGURACIÓN DE SALIDAS PARA TRANSISTORES DE CONTROL DEL DISPLAY 
	SBI DDRB, DDB0						// SALIDA TRANSISTOR DÍGITO 1 
	CBI PORTB, PB0							
	SBI DDRB, DDB1						// SALIDA TRANSISTOR DÍGITO 2 
	CBI PORTB, PB1 
	SBI DDRB, DDB2						// SALIDA TRANSISTOR DÍGITO 3 
	CBI PORTB, PB2
	SBI DDRB, DDB3						// SALIDA TRANSISTOR DÍGITO 4 
	CBI PORTB, PB3  

	// CONFIGURACIÓN DE SALIDA PARA LOS LEDS DE EN MEDIO 
	SBI DDRC, DDC5						// SALIDA PARA LOS LEDS EN PARALELO QUE ESTÁN EN MEDIO DE LOS 4 DISPLAYS
	CBI PORTC, PC5

	// CONFIGURACIÓN DE ENTRADA CON PULL-UP PARA LOS BOTONES DEL PORTC 
	CBI DDRC, DDC0 
	SBI PORTC, PORTC0
	CBI DDRC, DDC1 
	SBI PORTC, PORTC1
	CBI DDRC, DDC2 
	SBI PORTC, PORTC2
	CBI DDRC, DDC3 
	SBI PORTC, PORTC3
	CBI DDRC, DDC4 
	SBI PORTC, PORTC4

	// CONFIGURACIÓN DE SALIDA PARA LOS LEDS QUE MUESTRAN MODO 
	SBI DDRB, DDB4 
	CBI PORTB, PB4 
	SBI DDRB, DDB5 
	CBI PORTB, PB5

	// DESACTIVAR UART (PARA QUE NO HAYAN PROBLEMAS CON TX y RX)
	LDI R16, 0x00
	STS UCSR0B, R16

	// INICIALIZACIÓN DE VARIABLES 

	CLR R1									// R1 SIEMPRE ES CERO, PARA SUMAS CON ACARREO 
	CLR R16									
	STS OVERFLOW_TMR0, R16					
	STS INDICADOR_TMR1, R16					
	STS C_UNIDAD_MINUTO, R16				 
	STS C_DECENA_MINUTO, R16				 
	STS C_UNIDAD_HORA, R16					
	STS C_DECENA_HORA, R16					
	STS DISP_U_MIN, R16						
	STS DISP_D_MIN, R16						
	STS DISP_U_HR, R16						
	STS DISP_D_HR, R16						 
	STS DISP_SELEC, R16						
	STS MODO_ESTADO, R16					
	STS PINC_ANTERIOR, R16					 
	STS INDICADOR_BOTON1, R16				 	
	STS INDICADOR_BOTON2, R16				
	STS INDICADOR_BOTON3, R16				
	STS INDICADOR_BOTON4, R16				
	STS INDICADOR_BOTON5, R16				
	STS C_DECENA_MES, R16					
	STS C_DECENA_DIA, R16					
	STS DISP_U_MES, R16						
	STS DISP_D_MES, R16						
	STS DISP_U_DIA, R16						
	STS DISP_D_DIA, R16						
	STS MODO_DISPLAY, R16					
	STS INDICADOR_CAMBIO_DIA, R16			
	STS DISP_ESTADO3_1, R16					
	STS DISP_ESTADO3_2, R16					
	STS DISP_ESTADO3_3, R16					
	STS DISP_ESTADO3_4, R16					
	STS U_MES_ESTADO3, R16					
	STS D_MES_ESTADO3, R16 					
	STS U_DIA_ESTADO3, R16 					
	STS D_DIA_ESTADO3, R16 					
	STS DISP_ESTADO2_1, R16					
	STS DISP_ESTADO2_2, R16					
	STS DISP_ESTADO2_3, R16					
	STS DISP_ESTADO2_4, R16					
	STS U_MIN_ESTADO2, R16					
	STS D_MIN_ESTADO2, R16 					
	STS U_HR_ESTADO2, R16 					
	STS D_HR_ESTADO2, R16 					
	STS CONTADOR_ALARMA, R16				
	STS BUZZER_ENCENDIDO, R16
	// VALORES INICIALES PARA FECHA (1 DE ENERO)				
	LDI R16, 0x01 
	STS C_UNIDAD_MES, R16					
	STS C_UNIDAD_DIA, R16					
	LDI R16, 0x03 
	STS DISP_SELEC_ESTADO3, R16				
	STS DISP_SELEC_ESTADO2, R16
	// ALARMA_ VALORES INICIALES 0xFF PARA QUE NO COINCIDA CON NINGUNA HORA REAL 				
	LDI R16, 0xFF							
	STS U_MIN_ALARMA, R16 					
	STS D_MIN_ALARMA, R16 					
	STS U_HR_ALARMA, R16 					
	STS	D_HR_ALARMA, R16 					
	SEI										
/******/
// PROGRAMA PRINCIPAL (LOOP INFINITO)
MAIN_LOOP:									
	CALL RELOJ								// ACTUALIZA LA HORA SI HA PASADO UN MINUTO					
	CALL FECHA								// ACTUALIZA LA FECHA SI HA PASADO UN DÍA 
	CALL BOTON1								// PROCESO BOTÓN 1 SEGÚN ESTADO 
	CALL BOTON2								// PROCESO BOTÓN 2 SEGÚN ESTADO
	CALL BOTON3								// PROCESO BOTÓN 3 SEGÚN ESTADO
	CALL BOTON4								// PROCESO BOTÓN 4 SEGÚN ESTADO
	CALL BOTON5								// PROCESO BOTÓN 5 (CAMBIO DE ESTADO)
	CALL ALARMA								// COMPRUEBA SI ES HORA DE LA ALARMA 
	RJMP MAIN_LOOP
  
RELOJ: 
	LDS R16, INDICADOR_TMR1 
	CPI R16, 0x01							// COMPARA EL INDICADOR DE TIMER 1 CON 1 PARA SABER SI YA PASÓ UN MINUTO
	BRNE ACTUALIZACION_DISPLAYS 
	CLR R16									 
	STS INDICADOR_TMR1, R16					// SE LIMPIA EL INDICADOR DE TIMER 1
	LDS R16, C_UNIDAD_MINUTO				// INCREMENTA EL CONTADOR DE UNIDADES DE MINUTOS 
	INC R16									
	STS C_UNIDAD_MINUTO, R16
	CPI R16, 0x0A							// COMPARO EL CONTADOR DE UNIDADES DE MINUTO CON 10 PARA SABER SI YA HUBO OVERFLOW 
	BRNE ACTUALIZACION_DISPLAYS			
	CLR R16
	STS C_UNIDAD_MINUTO, R16 
	LDS R16, C_DECENA_MINUTO				// INCREMENTA DECENAS DE MINUTO 
	INC R16									
	STS C_DECENA_MINUTO, R16
	CPI R16, 0x6							// COMPARO EL CONTADOR DE DECENAS DE MINUTO CON 6 PARA SABER SI YA PASO UN MINUTO
	BRNE ACTUALIZACION_DISPLAYS 
	CLR R16									 
	STS C_DECENA_MINUTO, R16				// CUANDO LO MINUTOS PASEN DE 59, DEBE REINICIARSE EL CONTADOR DE DECENAS Y UNIDADES DE MINUTO
	STS C_UNIDAD_MINUTO, R16
	LDS R16, C_UNIDAD_HORA					// INCREMENTA EL CONTADOR DE UNIDADES DE HORA
	INC R16									 
	STS C_UNIDAD_HORA, R16 

	CPI R16, 0x4							// COMPRUEBA SI SON LAS 24:00 (UNIDAD=4 Y DECENA=2)
	BRNE LOGICA_NORMAL_HORA
	LDS R16, C_DECENA_HORA
	CPI R16, 0x2
	BRNE LOGICA_NORMAL_HORA
	
	CLR R16									// REINICIO A 00:00 Y ACTIVA CAMBIO DE DÍA 
	STS C_UNIDAD_MINUTO, R16 
	STS C_DECENA_MINUTO, R16 
	STS C_UNIDAD_HORA, R16
	STS C_DECENA_HORA, R16
	LDS R16, INDICADOR_CAMBIO_DIA			// SI PASO UN DÍA, SE ENCIENDE LA BANDERA INDICADOR_CAMBIO_DIA LA CUAL ES ÚTIL PARA LA RUTINA FECHA
	LDI R16, 0x01 
	STS INDICADOR_CAMBIO_DIA, R16 
	RJMP ACTUALIZACION_DISPLAYS 

LOGICA_NORMAL_HORA: 
	LDS R16, C_UNIDAD_HORA
	CPI R16, 0xA							// COMPARO EL CONTADOR DE UNIDADES DE HORA CON 10, SIGNIFICA QUE PUEDO SUMAR LAS DECENAS DE HORA 					
	BRNE ACTUALIZACION_DISPLAYS 
	CLR R16
	STS C_UNIDAD_HORA, R16
	LDS R16, C_DECENA_HORA
	INC R16									// INCREMENTA EL CONTADOR DE DECENAS DE HORA
	STS C_DECENA_HORA, R16		

ACTUALIZACION_DISPLAYS:						
	CALL MOSTRAR_CONTADOR_TIEMPO			// SE ACTUALIZAN LOS DISPLAYS PARA LA HORA 
	RET 

FECHA:										// RUTINA DE ACTUALIZACIÓN DE LA FECHA 								
	LDS R16, INDICADOR_CAMBIO_DIA			// SE EJECUTA CUANDO INDICADOR_CAMBIO_DIA= 1 (CADA 24 HORAS)
	CPI R16, 0x01 
	BREQ INCREMENTAR_FECHA
	RJMP ACTUALIZACION_DISPLAYS_FECHA
INCREMENTAR_FECHA: 
	CLR R16
	STS INDICADOR_CAMBIO_DIA, R16 
	LDS R16, C_UNIDAD_DIA					// SI PASO UN DÍA INCREMENTA EL CONTADOR DE UNIDAD DE DÍA
	INC R16 
	STS C_UNIDAD_DIA, R16  
	CPI R16, 0xA							// SI LLEGA A 10 HAY OVERFLOW, SE RECARGA Y DA PASO AL INCREMENTO DE LAS DECENAS DE DÍA 
	BRNE FIN_INCREMENTO_DIA
	CLR R16 
	STS C_UNIDAD_DIA, R16  
	LDS R16, C_DECENA_DIA 
	INC R16 
	STS C_DECENA_DIA, R16					 
	CPI R16, 0x4							// LAS DECENAS DE DÍA INCREMENTAN HASTA DETECTA QUE LLEGAN A 4, DE SER ASÍ, ESTA VARIABLE SE REINICIA 
	BRNE FIN_INCREMENTO_DIA
	CLR R16 
	STS C_DECENA_DIA, R16 
	LDS R16, C_UNIDAD_MES
	INC R16 
	STS C_UNIDAD_MES, R16					// INCREMENTA EL CONTADOR DE UNIDADES DE MES, DE SER IGUAL A 10, SE REINICIA 
	CPI R16, 0xA 
	BRNE FIN_INCREMENTO_DIA 
	CLR R16 
	STS C_UNIDAD_MES, R16 
	LDS R16, C_DECENA_MES 
	INC R16									// CUANDO HAY OVERFLOW DE LAS UNIDADES DE MES, INCREMENTA EL CONTADOR DE DECENAS DE MES, EL CUAL NO PUEDE SER MAYOR A 1 
	STS C_DECENA_MES, R16 
	CPI R16, 0x02
	BRNE FIN_INCREMENTO_DIA  
	CLR R16 
	STS C_DECENA_MES, R16

FIN_INCREMENTO_DIA:							// SI NO SE CUMPLEN CONDICIONES DE DESBORDAMIENTO, SE LLEGÁ A ESTA SUBRUTINA
	LDS R16, C_UNIDAD_DIA					// ESTA SUBRUTINA CONTROLA LOS DÍAS A LOS QUE CADA MES PUEDE LLEGAR 
	LDS R17, C_DECENA_DIA 
	LDS R18, C_UNIDAD_MES
	LDS R19, C_DECENA_MES  
ENERO:								
	CPI R19, 0x0 
	BRNE FEBRERO 
	CPI R18, 0x1 
	BRNE FEBRERO 
	CPI R17, 0x3 
	BRNE FEBRERO 
	CPI R16, 0x2 
	BRNE FEBRERO							// SI SE CUMPLEN TODAS LAS CONDICIONES PARA EL DESBORDAMIENTO DE ENERO, SE ESTABLECE FEBERO
	LDI R16, 0x1
	LDI R17, 0x0 
	LDI R18, 0x2
	LDI R19, 0x0 
	STS C_UNIDAD_DIA, R16  
	STS C_DECENA_DIA, R17 
	STS C_UNIDAD_MES, R18 
	STS C_DECENA_MES, R19
	RJMP ACTUALIZACION_DISPLAYS_FECHA		// SE ACTUALIZAN DISPLAYS PARA MOSTRAR LA FECHA ACTUAL 

FEBRERO:									// SIGUE LA MISMA LÓGICA QUE ENERO, TOMANDO EN CUENTA LOS DÍAS A LOS QUE FEBEREO PUEDE LLEGAR
	CPI R19, 0x0	
	BRNE MARZO 
	CPI R18, 0x2 
	BRNE MARZO 
	CPI R17, 0x2 
	BRNE MARZO 
	CPI R16, 0x9 
	BRNE MARZO 
	LDI R16, 0x1
	LDI R17, 0x0 
	LDI R18, 0x3
	LDI R19, 0x0 
	STS C_UNIDAD_DIA, R16  
	STS C_DECENA_DIA, R17 
	STS C_UNIDAD_MES, R18 
	STS C_DECENA_MES, R19
	RJMP ACTUALIZACION_DISPLAYS_FECHA

MARZO: 
	CPI R19, 0x0 
	BRNE ABRIL 
	CPI R18, 0x3 
	BRNE ABRIL 
	CPI R17, 0x3 
	BRNE ABRIL 
	CPI R16, 0x2 
	BRNE ABRIL 
	LDI R16, 0x1
	LDI R17, 0x0 
	LDI R18, 0x4
	LDI R19, 0x0 
	STS C_UNIDAD_DIA, R16  
	STS C_DECENA_DIA, R17 
	STS C_UNIDAD_MES, R18 
	STS C_DECENA_MES, R19
	RJMP ACTUALIZACION_DISPLAYS_FECHA

ABRIL: 
	CPI R19, 0x0 
	BRNE MAYO 
	CPI R18, 0x4 
	BRNE MAYO 
	CPI R17, 0x3 
	BRNE MAYO 
	CPI R16, 0x1 
	BRNE MAYO 
	LDI R16, 0x1
	LDI R17, 0x0 
	LDI R18, 0x5
	LDI R19, 0x0 
	STS C_UNIDAD_DIA, R16  
	STS C_DECENA_DIA, R17 
	STS C_UNIDAD_MES, R18 
	STS C_DECENA_MES, R19
	RJMP ACTUALIZACION_DISPLAYS_FECHA

MAYO: 
	CPI R19, 0x0 
	BRNE JUNIO 
	CPI R18, 0x5 
	BRNE JUNIO 
	CPI R17, 0x3 
	BRNE JUNIO 
	CPI R16, 0x2 
	BRNE JUNIO 
	LDI R16, 0x1
	LDI R17, 0x0 
	LDI R18, 0x6
	LDI R19, 0x0 
	STS C_UNIDAD_DIA, R16  
	STS C_DECENA_DIA, R17 
	STS C_UNIDAD_MES, R18 
	STS C_DECENA_MES, R19
	RJMP ACTUALIZACION_DISPLAYS_FECHA

JUNIO: 
	CPI R19, 0x0 
	BRNE JULIO 
	CPI R18, 0x6 
	BRNE JULIO
	CPI R17, 0x3 
	BRNE JULIO
	CPI R16, 0x1 
	BRNE JULIO 
	LDI R16, 0x1
	LDI R17, 0x0 
	LDI R18, 0x7
	LDI R19, 0x0 
	STS C_UNIDAD_DIA, R16  
	STS C_DECENA_DIA, R17 
	STS C_UNIDAD_MES, R18 
	STS C_DECENA_MES, R19
	RJMP ACTUALIZACION_DISPLAYS_FECHA

JULIO: 
	CPI R19, 0x0 
	BRNE AGOSTO 
	CPI R18, 0x7 
	BRNE AGOSTO
	CPI R17, 0x3 
	BRNE AGOSTO
	CPI R16, 0x2 
	BRNE AGOSTO 
	LDI R16, 0x1
	LDI R17, 0x0 
	LDI R18, 0x8
	LDI R19, 0x0 
	STS C_UNIDAD_DIA, R16  
	STS C_DECENA_DIA, R17 
	STS C_UNIDAD_MES, R18 
	STS C_DECENA_MES, R19
	RJMP ACTUALIZACION_DISPLAYS_FECHA

AGOSTO: 
	CPI R19, 0x0 
	BRNE SEPTIEMBRE 
	CPI R18, 0x8 
	BRNE SEPTIEMBRE
	CPI R17, 0x3 
	BRNE SEPTIEMBRE
	CPI R16, 0x2 
	BRNE SEPTIEMBRE 
	LDI R16, 0x1
	LDI R17, 0x0 
	LDI R18, 0x9
	LDI R19, 0x0 
	STS C_UNIDAD_DIA, R16  
	STS C_DECENA_DIA, R17 
	STS C_UNIDAD_MES, R18 
	STS C_DECENA_MES, R19
	RJMP ACTUALIZACION_DISPLAYS_FECHA

SEPTIEMBRE: 
	CPI R19, 0x0 
	BRNE OCTUBRE 
	CPI R18, 0x9 
	BRNE OCTUBRE
	CPI R17, 0x3 
	BRNE OCTUBRE
	CPI R16, 0x1 
	BRNE OCTUBRE 
	LDI R16, 0x1
	LDI R17, 0x0 
	LDI R18, 0x0
	LDI R19, 0x1 
	STS C_UNIDAD_DIA, R16  
	STS C_DECENA_DIA, R17 
	STS C_UNIDAD_MES, R18 
	STS C_DECENA_MES, R19
	RJMP ACTUALIZACION_DISPLAYS_FECHA

OCTUBRE: 
	CPI R19, 0x1 
	BRNE NOVIEMBRE 
	CPI R18, 0x0 
	BRNE NOVIEMBRE
	CPI R17, 0x3 
	BRNE NOVIEMBRE
	CPI R16, 0x2 
	BRNE NOVIEMBRE 
	LDI R16, 0x1
	LDI R17, 0x0 
	LDI R18, 0x1
	LDI R19, 0x1 
	STS C_UNIDAD_DIA, R16  
	STS C_DECENA_DIA, R17 
	STS C_UNIDAD_MES, R18 
	STS C_DECENA_MES, R19
	RJMP ACTUALIZACION_DISPLAYS_FECHA

NOVIEMBRE: 
	CPI R19, 0x1 
	BRNE DICIEMBRE 
	CPI R18, 0x1 
	BRNE DICIEMBRE
	CPI R17, 0x3 
	BRNE DICIEMBRE
	CPI R16, 0x1 
	BRNE DICIEMBRE 
	LDI R16, 0x1
	LDI R17, 0x0 
	LDI R18, 0x2
	LDI R19, 0x1 
	STS C_UNIDAD_DIA, R16  
	STS C_DECENA_DIA, R17 
	STS C_UNIDAD_MES, R18 
	STS C_DECENA_MES, R19
	RJMP ACTUALIZACION_DISPLAYS_FECHA

DICIEMBRE: 
	CPI R19, 0x1 
	BRNE FINALIZAR_FECHA 
	CPI R18, 0x2 
	BRNE FINALIZAR_FECHA 
	CPI R17, 0x3 
	BRNE FINALIZAR_FECHA 
	CPI R16, 0x2 
	BRNE FINALIZAR_FECHA  
	LDI R16, 0x1
	LDI R17, 0x0 
	LDI R18, 0x1
	LDI R19, 0x0 
	STS C_UNIDAD_DIA, R16  
	STS C_DECENA_DIA, R17 
	STS C_UNIDAD_MES, R18 
	STS C_DECENA_MES, R19
	RJMP ACTUALIZACION_DISPLAYS_FECHA
FINALIZAR_FECHA: 
ACTUALIZACION_DISPLAYS_FECHA:
	CALL MOSTRAR_CONTADOR_FECHA					// SE LLAMA A SUBRUTINA QUE ACTUALIZA LOS DISPLAYSQUE MUESTRAN LA FECHA 
	RET 

// RUTINAS DE PROCESAMIENTO DE BOTONES (MÁQUINA DE ESTADOS)
BOTON1:											// BOTÓN 1 (INCREMENTAR)
	LDS R16, INDICADOR_BOTON1					
	CPI R16, 0x01 
	BRNE LIMPIEZA_BOTON1 
	LDS R16, MODO_ESTADO 
	CPI R16, 0x0 
	BREQ BOTON1_ESTADO0 
	CPI R16, 0x01 
	BREQ BOTON1_ESTADO1
	CPI R16, 0x02 
	BREQ BOTON1_ESTADO2 
	CPI R16, 0x03
	BREQ BOTON1_ESTADO3
	RJMP LIMPIEZA_BOTON1 
BOTON1_ESTADO0:									// MODO HORA: SIN ACCIÓN 
	RJMP LIMPIEZA_BOTON1 
BOTON1_ESTADO1:									// MODO FECHA: SIN ACCIÓN 
	RJMP LIMPIEZA_BOTON1 
BOTON1_ESTADO2:									// MODO CONFIGURACIÓN HORA: INCREMENTA DÍGITO SELECCIONADO 
	CALL INCREMENTAR_ESTADO_CONFIGURACION_HORA_ALARMA
	RJMP LIMPIEZA_BOTON1
BOTON1_ESTADO3:									// MODO CONFIGURACIÓN FECHA: INCREMENTA DÍGITO SELECCIONADO 
	CALL INCREMENTAR_ESTADO_CONFIGURACION_FECHA
	RJMP LIMPIEZA_BOTON1
LIMPIEZA_BOTON1: 
	CLR R16 
	STS INDICADOR_BOTON1, R16 
	RET
BOTON2:											// BOTÓN 2 (DECREMENTAR O CONFIRMAR HORA) 
	LDS R16, INDICADOR_BOTON2 
	CPI R16, 0x01 
	BRNE LIMPIEZA_BOTON2 
	LDS R16, MODO_ESTADO 
	CPI R16, 0x0 
	BREQ BOTON2_ESTADO0 
	CPI R16, 0x01 
	BREQ BOTON2_ESTADO1
	CPI R16, 0x02 
	BREQ BOTON2_ESTADO2 
	CPI R16, 0x03
	BREQ BOTON2_ESTADO3
	RJMP LIMPIEZA_BOTON2 
BOTON2_ESTADO0:									// MODO HORA: SIN ACCIÓN 
	RJMP LIMPIEZA_BOTON2 
BOTON2_ESTADO1:									// MODO FECHA: SIN ACCIÓN 
	RJMP LIMPIEZA_BOTON2 
BOTON2_ESTADO2:									// MODO CONFIGURACIÓN HORA: CONFIRMA LA HORA ACTUAL (COPIA A CONTADORES REALES)
	CALL CONFIRMAR_HORA 
	RJMP LIMPIEZA_BOTON2
BOTON2_ESTADO3:									// MODO CONFIGURACIÓN FECHA: DECREMENTA DÍGITO SELECCIONADO 
	CALL DECREMENTAR_ESTADO_CONFIGURACION_FECHA
	RJMP LIMPIEZA_BOTON2
LIMPIEZA_BOTON2: 
	CLR R16 
	STS INDICADOR_BOTON2, R16 
	RET

BOTON3:											// BOTÓN 3 (CAMBIAR DÍGITO SELECCIONADO)
	LDS R16, INDICADOR_BOTON3 
	CPI R16, 0x01 
	BRNE LIMPIEZA_BOTON3 
	LDS R16, MODO_ESTADO 
	CPI R16, 0x0 
	BREQ BOTON3_ESTADO0 
	CPI R16, 0x01 
	BREQ BOTON3_ESTADO1
	CPI R16, 0x02 
	BREQ BOTON3_ESTADO2 
	CPI R16, 0x03
	BREQ BOTON3_ESTADO3
	RJMP LIMPIEZA_BOTON3 
BOTON3_ESTADO0:									// MODO HORA: SIN ACCIÓN 
	RJMP LIMPIEZA_BOTON3 
BOTON3_ESTADO1:									// MODO FECHA: SIN ACCÓN 
	RJMP LIMPIEZA_BOTON3 
BOTON3_ESTADO2:									// MODO CONFIGURACIÓN HORA: CAMBIA DÍGITO SELECCIONADO 
	CALL CAMBIAR_DISPLAY_MODO_CONFIGURACION_HORA
	RJMP LIMPIEZA_BOTON3
BOTON3_ESTADO3:									// MODO CONFIGURACIÓN FECHA: CAMBIA DÍGITO SELECCIONADO 
	CALL CAMBIAR_DISPLAY_MODO_CONFIGURACION_FECHA
	RJMP LIMPIEZA_BOTON3
LIMPIEZA_BOTON3: 
	CLR R16 
	STS INDICADOR_BOTON3, R16 
	RET

BOTON4:											// BOTÓN 4 (CONFIRMAR ALARMA O FECHA )
	LDS R16, INDICADOR_BOTON4 
	CPI R16, 0x01 
	BRNE LIMPIEZA_BOTON4 
	LDS R16, MODO_ESTADO 
	CPI R16, 0x0 
	BREQ BOTON4_ESTADO0 
	CPI R16, 0x01 
	BREQ BOTON4_ESTADO1
	CPI R16, 0x02 
	BREQ BOTON4_ESTADO2 
	CPI R16, 0x03
	BREQ BOTON4_ESTADO3
	RJMP LIMPIEZA_BOTON4 
BOTON4_ESTADO0:									// MODO HORA: SIN ACCIÓN 
	RJMP LIMPIEZA_BOTON4 
BOTON4_ESTADO1:									// MODO FECHA: SIN ACCIÓN 
	RJMP LIMPIEZA_BOTON4 
BOTON4_ESTADO2:									// MODO CONFIGURACIÓN HORA: GUARDA HORA CON ALARMA 
	CALL CONFIRMAR_ALARMA_MODO_HORA
	RJMP LIMPIEZA_BOTON4
BOTON4_ESTADO3:									// MODO CONFIGURACIÓN FECHA: CONFIRMA NUEVA FECHA 
	CALL CONFIRMAR_FECHA_MODO_FECHA
	RJMP LIMPIEZA_BOTON4
LIMPIEZA_BOTON4: 
	CLR R16 
	STS INDICADOR_BOTON4, R16 
	RET

BOTON5:											// BOTÓN 5 (CAMBIAR MODO/ESTADO)
	LDS R16, INDICADOR_BOTON5 
	CPI R16, 0x01				
	BREQ CAMBIAR_ESTADO							// SOLO VA A CAMBIAR DE ESTADO SI LA BANDERA ESTÁ ACTIVA
	CLR R16 
	STS INDICADOR_BOTON5, R16 
	RET 
CAMBIAR_ESTADO: 
	CLR R16 
	STS INDICADOR_BOTON5, R16 
	LDS R16, MODO_ESTADO 
	INC R16 
	STS MODO_ESTADO, R16
	CPI R16, 0x04								// SI LLEGA A 4, VUELVE A 0 
	BRNE ESTADO_LEDS
	CLR R16
	STS MODO_ESTADO, R16 
ESTADO_LEDS:									// ACTUALIZA LEDS DE MODO EN PB4-PB5 
	MOV R17, R16 
	LSL R17 
	LSL R17 
	LSL R17 
	LSL R17										// DESPLAZA EL VALOR DEL ESTADO A LOS BITS 4-5
	IN R18, PORTB 
	ANDI R18, 0b1100_1111						// LIMPIA BITS 4 Y 5 
	OR R18, R17 
	OUT PORTB, R18 
INDICADOR_DISPLAYS:								// ACTUALIZA MODO_DISPLAY SEGÚN EL NUEVO ESTADO Y CARGA VALORES EN DISPLAYS TEMPORALES  
	LDS R16, MODO_ESTADO 
	CPI R16, 0x0
	BRNE COMPARAR_ESTADO1
	LDI R17, 0x0 
	STS MODO_DISPLAY, R17						// MODO 0_ MOSTRAR HORA 
	RJMP SALIDA_BOTON5 
COMPARAR_ESTADO1:
	CPI R16, 0x01 
	BRNE COMPARAR_ESTADO2 
	LDI R17, 0x01
	STS MODO_DISPLAY, R17						// MODO 1: MOSTRAR FECHA 
	RJMP SALIDA_BOTON5
COMPARAR_ESTADO2: 
	CPI R16, 0x02 
    BRNE COMPARAR_ESTADO3
    LDI R17, 0x02
    STS MODO_DISPLAY, R17						// MODO 2: CONFIGURAR HORA 
    LDS R17, C_DECENA_MINUTO					// CARGA VALORES ACTUALES DE HORA EN VARIABLES TEMPORALES 
    STS D_MIN_ESTADO2, R17
    LDS R17, C_UNIDAD_MINUTO 
    STS U_MIN_ESTADO2, R17
    LDS R17, C_DECENA_HORA
    STS D_HR_ESTADO2, R17
    LDS R17, C_UNIDAD_HORA
    STS U_HR_ESTADO2, R17
    CLR R17
    STS DISP_SELEC_ESTADO2, R17					// SELECTOR EMPIEZA EN DÍGITO 0   
    CALL CAMBIAR_DISPLAY_MODO_CONFIGURACION_HORA	// ACTUALIZA DISPLAYS 
    RJMP SALIDA_BOTON5 
COMPARAR_ESTADO3: 
    CPI R16, 0x03 
    BRNE SALIDA_BOTON5 
    LDI R17, 0x03
    STS MODO_DISPLAY, R17						// MODO 3: CONFIGURAR FECHA 
    LDS R17, C_DECENA_MES						// CARGA VALORES ACTUALES DE FECHA EN VARIABLES TEMPORALES 
    STS D_MES_ESTADO3, R17
    LDS R17, C_UNIDAD_MES
    STS U_MES_ESTADO3, R17
    LDS R17, C_DECENA_DIA
    STS D_DIA_ESTADO3, R17
    LDS R17, C_UNIDAD_DIA
    STS U_DIA_ESTADO3, R17
    CLR R17
    STS DISP_SELEC_ESTADO3, R17					// SELECTOR EMPIEZA EN DÍGITO 0 
    CALL CAMBIAR_DISPLAY_MODO_CONFIGURACION_FECHA  // ACTUALIZA DISPLAYS 
    RJMP SALIDA_BOTON5 
SALIDA_BOTON5:
	RET 

ALARMA:											// RUTINA DE ALARMA: COMPARA LA HORA ACTUAL CON LA ALARMA, SI COINCIDEN Y EL BUZZER NO ESTÁ SONANDO, ACTIVA EL CONTADOR DE ALARMA Y ENCIENDE EL BUZZER. 
	LDS R16, U_MIN_ALARMA  
	LDS R17, C_UNIDAD_MINUTO
	CP R16, R17
	BRNE SALIDA_ALARMA
	LDS R16, D_MIN_ALARMA  
	LDS R17, C_DECENA_MINUTO
	CP R16, R17
	BRNE SALIDA_ALARMA
	LDS R16, U_HR_ALARMA	 
	LDS R17, C_UNIDAD_HORA
	CP R16, R17
	BRNE SALIDA_ALARMA
	LDS R16, D_HR_ALARMA	 
	LDS R17, C_DECENA_HORA
	CP R16, R17
	BRNE SALIDA_ALARMA
	LDS R16, BUZZER_ENCENDIDO 
	CPI R16, 0x0 
	BRNE SALIDA_ALARMA 
	LDI R16, 0x01								// DURACIÓN DE LA ALARMA (1 INTERRUPCIÓN DE TIMER0=250MS)
	STS CONTADOR_ALARMA, R16 
	LDI R16, 0x01 
	STS BUZZER_ENCENDIDO, R16  					// ENCIENDE BUZZER (BIT 7 DE PORTD)
	SBI PORTD, PORTD7
SALIDA_ALARMA: 
	RET 
/******/
// SUBRUTINAS NO INTERRUPTORAS 
INCREMENTAR_ESTADO_CONFIGURACION_HORA_ALARMA:	// INCREMENTO EN MODO CONFIGURACIÓN HORA (BOTÓN 1)
	LDS R16, DISP_SELEC_ESTADO2
    CPI R16, 0
    BREQ INC_DIG1_E2
    CPI R16, 1
    BREQ INC_DIG2_E2
    CPI R16, 2
    BREQ INC_DIG3_E2
    CPI R16, 3
    BREQ INC_DIG4_E2
    RET
INC_DIG1_E2:									// UNIDAD DE MINUTO 
    LDS R16, U_MIN_ESTADO2
    INC R16
    CPI R16, 0xA
    BRNE GUARDAR_DIG1_E2
    CLR R16
GUARDAR_DIG1_E2:
    STS U_MIN_ESTADO2, R16
    CALL CONVERTIR_A_7SEG
    LDS R17, DISP_SELEC_ESTADO2
    CPI R17, 0x0
    BRNE DIG1_SIN_SEGMENTO_E2
    ORI R16, 0x20								// AÑADE SEGMENTO D SI ES EL DÍGITO SELECCIONADO (EL SEGMENTO D INDICA SI UN DÍGITO ESTÁ SIENDO EDITADO )
DIG1_SIN_SEGMENTO_E2:
    STS DISP_ESTADO2_1, R16
    CALL VERIFICAR_ESTADOS_INVALIDOS_E2
	RET 
INC_DIG2_E2:									// DECENA DE MINUTO 
    LDS R16, D_MIN_ESTADO2
    INC R16
    CPI R16, 0x6
    BRNE GUARDAR_DIG2_E2
    CLR R16 
GUARDAR_DIG2_E2:
    STS D_MIN_ESTADO2, R16
    CALL CONVERTIR_A_7SEG
    LDS R17, DISP_SELEC_ESTADO2
    CPI R17, 0x1
    BRNE DIG2_SIN_SEGMENTO_E2
    ORI R16, 0x20								// AÑADE SEGMENTO D SI ES EL DÍGITO SELECCIONADO 
DIG2_SIN_SEGMENTO_E2:
    STS DISP_ESTADO2_2, R16
    CALL VERIFICAR_ESTADOS_INVALIDOS_E2
	RET
INC_DIG3_E2:									// UNIDAD DE HORA 
    LDS R16, U_HR_ESTADO2
    INC R16
    CPI R16, 0xA 
    BRNE GUARDAR_DIG3_E2
    CLR R16
GUARDAR_DIG3_E2:
    STS U_HR_ESTADO2, R16
    CALL CONVERTIR_A_7SEG
    LDS R17, DISP_SELEC_ESTADO2
    CPI R17, 0x2
    BRNE DIG3_SIN_SEGMENTO_E2
    ORI R16, 0x20								// AÑADE SEGMENTO D SI ES EL DÍGITO SELECCIONADO 
DIG3_SIN_SEGMENTO_E2:
    STS DISP_ESTADO2_3, R16
    CALL VERIFICAR_ESTADOS_INVALIDOS_E2
	RET 
INC_DIG4_E2:									// DECENA DE HORA  
    LDS R16, D_HR_ESTADO2
    INC R16
    CPI R16, 0x3
    BRNE GUARDAR_DIG4_E2
    CLR R16
GUARDAR_DIG4_E2:
    STS D_HR_ESTADO2, R16
    CALL CONVERTIR_A_7SEG
    LDS R17, DISP_SELEC_ESTADO2
    CPI R17, 0x3
    BRNE DIG4_SIN_SEGMENTO_E2
    ORI R16, 0x20								// AÑADE SEGMENTO D SI ES EL DÍGITO SELECCIONADO 
DIG4_SIN_SEGMENTO_E2:
    STS DISP_ESTADO2_4, R16
	CALL VERIFICAR_ESTADOS_INVALIDOS_E2
	RET 

INCREMENTAR_ESTADO_CONFIGURACION_FECHA:			// INCREMENTO EN MODO CONFIGURACIÓN FECHA (BOTÓN 1)			 
    LDS R16, DISP_SELEC_ESTADO3
    CPI R16, 0
    BREQ INC_DIG1
    CPI R16, 1
    BREQ INC_DIG2
    CPI R16, 2
    BREQ INC_DIG3
    CPI R16, 3
    BREQ INC_DIG4
    RET
INC_DIG1:										// UNIDAD DE MES 
    LDS R16, U_MES_ESTADO3
    INC R16
    CPI R16, 0xA
    BRNE GUARDAR_DIG1
    CLR R16
GUARDAR_DIG1:
    STS U_MES_ESTADO3, R16
    CALL CONVERTIR_A_7SEG
    LDS R17, DISP_SELEC_ESTADO3
    CPI R17, 0x0
    BRNE DIG1_SIN_SEGMENTO
    ORI R16, 0x20
DIG1_SIN_SEGMENTO:
    STS DISP_ESTADO3_1, R16
    CALL VERIFICAR_ESTADOS_INVALIDOS
	RET 
INC_DIG2:										// DECENA DE MES 
    LDS R16, D_MES_ESTADO3
    INC R16
    CPI R16, 0x2
    BRNE GUARDAR_DIG2
    CLR R16 
GUARDAR_DIG2:
    STS D_MES_ESTADO3, R16
    CALL CONVERTIR_A_7SEG
    LDS R17, DISP_SELEC_ESTADO3
    CPI R17, 0x1
    BRNE DIG2_SIN_SEGMENTO
    ORI R16, 0x20
DIG2_SIN_SEGMENTO:
    STS DISP_ESTADO3_2, R16
    CALL VERIFICAR_ESTADOS_INVALIDOS
	RET
INC_DIG3:										// UNIDAD DE DÍA 
    LDS R16, U_DIA_ESTADO3
    INC R16
    CPI R16, 0xA 
    BRNE GUARDAR_DIG3
    CLR R16
GUARDAR_DIG3:
    STS U_DIA_ESTADO3, R16
    CALL CONVERTIR_A_7SEG
    LDS R17, DISP_SELEC_ESTADO3
    CPI R17, 0x2
    BRNE DIG3_SIN_SEGMENTO
    ORI R16, 0x20
DIG3_SIN_SEGMENTO:
    STS DISP_ESTADO3_3, R16
    CALL VERIFICAR_ESTADOS_INVALIDOS
	RET 
INC_DIG4:										// DECENA DE DÍA 
    LDS R16, D_DIA_ESTADO3
    INC R16
    CPI R16, 0x4
    BRNE GUARDAR_DIG4
    CLR R16
GUARDAR_DIG4:
    STS D_DIA_ESTADO3, R16
    CALL CONVERTIR_A_7SEG
    LDS R17, DISP_SELEC_ESTADO3
    CPI R17, 0x3
    BRNE DIG4_SIN_SEGMENTO
    ORI R16, 0x20
DIG4_SIN_SEGMENTO:
    STS DISP_ESTADO3_4, R16
	CALL VERIFICAR_ESTADOS_INVALIDOS
	RET 

CONFIRMAR_HORA:									// CONFIRMAR HORA EDITADA (BOTÓN 2 EN MODO 2)
	LDS R16, C_UNIDAD_MINUTO					// SE COPIA AL CONTADOR DE UNIDAD DE MINTO EL VALOR MODIFICADO PARA UNIDAD DE MINUTO 
	LDS R17, U_MIN_ESTADO2
	MOV R16, R17 
	STS C_UNIDAD_MINUTO, R16 
	LDS R16, C_DECENA_MINUTO					// SE COPIA AL CONTADOR DE DECENA DE MINUTO EL VALOR MODIFICADO PARA DECENA DE MINUTO
	LDS R17, D_MIN_ESTADO2
	MOV R16, R17 
	STS C_DECENA_MINUTO, R16 
	LDS R16, C_UNIDAD_HORA						// SE COPIA AL CONTADOR DE UNIDAD DE HORA EL VALOR MODIFICADO PARA UNIDAD DE HORA 
	LDS R17, U_HR_ESTADO2
	MOV R16, R17 
	STS C_UNIDAD_HORA, R16 
	LDS R16, C_DECENA_HORA						// SE COPIA AL CONTADOR DE DECENA DE HORA EL VALOR MODIFICADO PARA DECENA DE HORA 
	LDS R17, D_HR_ESTADO2
	MOV R16, R17 
	STS C_DECENA_HORA, R16 
	RET

DECREMENTAR_ESTADO_CONFIGURACION_FECHA:			// DECREMENTO EN MODO CONFIGURACIÓN FECHA (BOTÓN 2)
    LDS R16, DISP_SELEC_ESTADO3
    CPI R16, 0
    BREQ DEC_DIG1
    CPI R16, 1
    BREQ DEC_DIG2
    CPI R16, 2
    BREQ DEC_DIG3
    CPI R16, 3
    BREQ DEC_DIG4
    RET
DEC_DIG1:  
    LDS R16, U_MES_ESTADO3
    DEC R16
    CPI R16, 0xFF								// SI BAJA DE 0, VUELVE A 9
    BRNE GUARDAR_DIG1_DEC
    LDI R16, 0x09
GUARDAR_DIG1_DEC:
    STS U_MES_ESTADO3, R16
    CALL CONVERTIR_A_7SEG
    LDS R17, DISP_SELEC_ESTADO3
    CPI R17, 0x0
    BRNE DIG1_SIN_SEGMENTO_DEC
    ORI R16, 0x20
DIG1_SIN_SEGMENTO_DEC:
    STS DISP_ESTADO3_1, R16
    CALL VERIFICAR_ESTADOS_INVALIDOS
	RET 
DEC_DIG2: 
    LDS R16, D_MES_ESTADO3
    DEC R16
    CPI R16, 0xFF
    BRNE GUARDAR_DIG2_DEC
    LDI R16, 0x01								// DECENA DE MES SOLO PUEDE SER 0 O 1 
GUARDAR_DIG2_DEC:
    STS D_MES_ESTADO3, R16
    CALL CONVERTIR_A_7SEG
    LDS R17, DISP_SELEC_ESTADO3
    CPI R17, 0x1
    BRNE DIG2_SIN_SEGMENTO_DEC
    ORI R16, 0x20
DIG2_SIN_SEGMENTO_DEC:
    STS DISP_ESTADO3_2, R16
    CALL VERIFICAR_ESTADOS_INVALIDOS
	RET
DEC_DIG3:  
    LDS R16, U_DIA_ESTADO3
    DEC R16
    CPI R16, 0xFF
    BRNE GUARDAR_DIG3_DEC
    LDI R16, 0x09
GUARDAR_DIG3_DEC:
    STS U_DIA_ESTADO3, R16
    CALL CONVERTIR_A_7SEG
    LDS R17, DISP_SELEC_ESTADO3
    CPI R17, 0x2
    BRNE DIG3_SIN_SEGMENTO_DEC
    ORI R16, 0x20
DIG3_SIN_SEGMENTO_DEC:
    STS DISP_ESTADO3_3, R16
    CALL VERIFICAR_ESTADOS_INVALIDOS
	RET 
DEC_DIG4:  
    LDS R16, D_DIA_ESTADO3
    DEC R16
    CPI R16, 0xFF
    BRNE GUARDAR_DIG4_DEC
    LDI R16, 0x03								// DECENA DE DÍA PUEDE SER 0-3
GUARDAR_DIG4_DEC:
    STS D_DIA_ESTADO3, R16
    CALL CONVERTIR_A_7SEG
    LDS R17, DISP_SELEC_ESTADO3
    CPI R17, 0x3
    BRNE DIG4_SIN_SEGMENTO_DEC
    ORI R16, 0x20
DIG4_SIN_SEGMENTO_DEC:
    STS DISP_ESTADO3_4, R16
	CALL VERIFICAR_ESTADOS_INVALIDOS
	RET 

CAMBIAR_DISPLAY_MODO_CONFIGURACION_HORA:		// CAMBIAR DÍGITO SELECCIONADO EN MODO CONFIGURACIÓN HORA (BOTÓN 3)
	LDS R16, DISP_SELEC_ESTADO2
    INC R16
    STS DISP_SELEC_ESTADO2, R16
    CPI R16, 4
    BRNE CONTINUAR_CAMBIO_E2
    CLR R16
    STS DISP_SELEC_ESTADO2, R16
CONTINUAR_CAMBIO_E2:							// ACTUALIZA TODOS LOS DISPLAYS CON EL SEGMENTO D EN EL DÍGITO SELECCIONADO 
    LDS R16, U_MIN_ESTADO2
    CALL CONVERTIR_A_7SEG
    LDS R17, DISP_SELEC_ESTADO2
    CPI R17, 0
    BRNE DIG1_NO_SEGMENTO_E2
    ORI R16, 0x20
DIG1_NO_SEGMENTO_E2:
    STS DISP_ESTADO2_1, R16
    LDS R16, D_MIN_ESTADO2
    CALL CONVERTIR_A_7SEG
    LDS R17, DISP_SELEC_ESTADO2
    CPI R17, 1
    BRNE DIG2_NO_SEGMENTO_E2
    ORI R16, 0x20
DIG2_NO_SEGMENTO_E2:
    STS DISP_ESTADO2_2, R16
    LDS R16, U_HR_ESTADO2
    CALL CONVERTIR_A_7SEG
    LDS R17, DISP_SELEC_ESTADO2
    CPI R17, 2
    BRNE DIG3_NO_SEGMENTO_E2
    ORI R16, 0x20
DIG3_NO_SEGMENTO_E2:
    STS DISP_ESTADO2_3, R16
    LDS R16, D_HR_ESTADO2
    CALL CONVERTIR_A_7SEG
    LDS R17, DISP_SELEC_ESTADO2
    CPI R17, 3
    BRNE DIG4_NO_SEGMENTO_E2
    ORI R16, 0x20
DIG4_NO_SEGMENTO_E2:
    STS DISP_ESTADO2_4, R16
    RET

CAMBIAR_DISPLAY_MODO_CONFIGURACION_FECHA:		// CAMBIAR DÍGITO SELECCIONADO EN MODO CONFIGURACIÓN FECHA (BOTÓN 3)
    LDS R16, DISP_SELEC_ESTADO3
    INC R16
    STS DISP_SELEC_ESTADO3, R16
    CPI R16, 4
    BRNE CONTINUAR_CAMBIO
    CLR R16
    STS DISP_SELEC_ESTADO3, R16
CONTINUAR_CAMBIO:
    LDS R16, U_MES_ESTADO3
    CALL CONVERTIR_A_7SEG
    LDS R17, DISP_SELEC_ESTADO3
    CPI R17, 0
    BRNE DIG1_NO_SEGMENTO
    ORI R16, 0x20
DIG1_NO_SEGMENTO:
    STS DISP_ESTADO3_1, R16
    LDS R16, D_MES_ESTADO3
    CALL CONVERTIR_A_7SEG
    LDS R17, DISP_SELEC_ESTADO3
    CPI R17, 1
    BRNE DIG2_NO_SEGMENTO
    ORI R16, 0x20
DIG2_NO_SEGMENTO:
    STS DISP_ESTADO3_2, R16
    LDS R16, U_DIA_ESTADO3
    CALL CONVERTIR_A_7SEG
    LDS R17, DISP_SELEC_ESTADO3
    CPI R17, 2
    BRNE DIG3_NO_SEGMENTO
    ORI R16, 0x20
DIG3_NO_SEGMENTO:
    STS DISP_ESTADO3_3, R16
    LDS R16, D_DIA_ESTADO3
    CALL CONVERTIR_A_7SEG
    LDS R17, DISP_SELEC_ESTADO3
    CPI R17, 3
    BRNE DIG4_NO_SEGMENTO
    ORI R16, 0x20
DIG4_NO_SEGMENTO:
    STS DISP_ESTADO3_4, R16
    RET

CONFIRMAR_ALARMA_MODO_HORA:					// CONFIRMAR ALARMA (GUARDA LA HORA EDITADA EN VARIABLES DE ALARMA )
	LDS R16, U_MIN_ALARMA					// SE COPIA AL CONTADOR DE UNIDAD DE MINTO DE LA ALARMA EL VALOR MODIFICADO PARA UNIDAD DE MINUTO 
	LDS R17, U_MIN_ESTADO2
	MOV R16, R17 
	STS U_MIN_ALARMA, R16 
	LDS R16, D_MIN_ALARMA 					// SE COPIA AL CONTADOR DE DECENA DE LA ALARMA EL VALOR MODIFICADO PARA DECENA DE MINUTO
	LDS R17, D_MIN_ESTADO2
	MOV R16, R17 
	STS D_MIN_ALARMA, R16 
	LDS R16, U_HR_ALARMA					// SE COPIA AL CONTADOR DE UNIDAD DE HORA DE LA ALARMA EL VALOR MODIFICADO PARA UNIDAD DE HORA 
	LDS R17, U_HR_ESTADO2
	MOV R16, R17 
	STS U_HR_ALARMA, R16 
	LDS R16, D_HR_ALARMA					// SE COPIA AL CONTADOR DE DECENA DE HORA DE LA ALARMA  EL VALOR MODIFICADO PARA DECENA DE HORA 
	LDS R17, D_HR_ESTADO2
	MOV R16, R17 
	STS D_HR_ALARMA, R16 
	RET

	RET
CONFIRMAR_FECHA_MODO_FECHA:					// CONFIRMAR FECHA EDITADA (GUARDA EN VARIABLES REALES)
	LDS R16, C_UNIDAD_MES					// SE COPIA AL CONTADOR DE UNIDAD DE MES EL VALOR MODIFICADO PARA UNIDAD DE MES
	LDS R17, U_MES_ESTADO3
	MOV R16, R17 
	STS C_UNIDAD_MES, R16 
	LDS R16, C_DECENA_MES					// SE COPIA AL CONTADOR DE DECECA DE MES EL VALOR MODIFICADO PARA DECENA DE MES
	LDS R17, D_MES_ESTADO3
	MOV R16, R17 
	STS C_DECENA_MES, R16 
	LDS R16, C_UNIDAD_DIA					// SE COPIA AL CONTADOR DE UNIDAD DE DÍA EL VALOR MODIFICADO PARA UNIDAD DE DÍA 
	LDS R17, U_DIA_ESTADO3
	MOV R16, R17 
	STS C_UNIDAD_DIA, R16 
	LDS R16, C_DECENA_DIA					// SE COPIA AL CONTADOR DE DECENA DE DÍA EL VALOR MODIFICADO PARA DECENA DE DÍA
	LDS R17, D_DIA_ESTADO3
	MOV R16, R17 
	STS C_DECENA_DIA, R16 
	RET

MOSTRAR_CONTADOR_TIEMPO:					// ACTUALIZA VARIABLES TEMPORALES DE DISPLAYS DE TIEMPO (CONVIERTE CONTADORES A 7 SEGMENTOS)
	// TIEMPO 
	LDI ZH, HIGH(tabla7<<1)					// SE REINICIA LA POSICIÓN DEL PUNTERO 
	LDI ZL, LOW(tabla7<<1)
	LDS R16, C_UNIDAD_MINUTO
	ADD ZL, R16								// LE SUMAMOS AL BYTE BAJO EL CONTADOR DE UNIDADES DE MINUTO 
	ADC ZH, R1								// R1 SIEMPRE TIENE CERO, PERO SI LA SUMA ANTERIOR TIENE CARRY, AL BYTE ALTO DE Z, ZH, SE LE SUMA ESE CARRY 
	LPM R16, Z								// SE CARGA EL VALOR DE LA NUEVA POSICIÓN DE Z AL REGISTRO DE UNIDADES DE MINUTO 
	STS DISP_U_MIN, R16

	LDI ZH, HIGH(tabla7<<1)					// SE REINICIA LA POSICIÓN DEL PUNTERO 
	LDI ZL, LOW(tabla7<<1)
	LDS R16, C_DECENA_MINUTO
	ADD ZL, R16								// LE SUMAMOS AL BYTE BAJO EL CONTADOR DE DECENAS DE MINUTO 
	ADC ZH, R1								// R1 SIEMPRE TIENE CERO, PERO SI LA SUMA ANTERIOR TIENE CARRY, AL BYTE ALTO DE Z, ZH, SE LE SUMA ESE CARRY 
	LPM R16, Z								// SE CARGA EL VALOR DE LA NUEVA POSICIÓN DE Z AL REGISTRO DE DECENAS DE MINUTO
	STS DISP_D_MIN, R16

	LDI ZH, HIGH(tabla7<<1)					// SE REINICIA LA POSICIÓN DEL PUNTERO 
	LDI ZL, LOW(tabla7<<1)
	LDS R16, C_UNIDAD_HORA
	ADD ZL, R16								// LE SUMAMOS AL BYTE BAJO EL CONTADOR DE UNIDADES DE HORA  
	ADC ZH, R1								// R1 SIEMPRE TIENE CERO, PERO SI LA SUMA ANTERIOR TIENE CARRY, AL BYTE ALTO DE Z, ZH, SE LE SUMA ESE CARRY 
	LPM R16, Z								// SE CARGA EL VALOR DE LA NUEVA POSICIÓN DE Z AL REGISTRO DE UNIDADES DE HORA 
	STS DISP_U_HR, R16

	LDI ZH, HIGH(tabla7<<1)					// SE REINICIA LA POSICIÓN DEL PUNTERO 
	LDI ZL, LOW(tabla7<<1)
	LDS R16, C_DECENA_HORA
	ADD ZL, R16								// LE SUMAMOS AL BYTE BAJO EL CONTADOR DE DECENAS DE HORA  
	ADC ZH, R1								// R1 SIEMPRE TIENE CERO, PERO SI LA SUMA ANTERIOR TIENE CARRY, AL BYTE ALTO DE Z, ZH, SE LE SUMA ESE CARRY 
	LPM R16, Z								// SE CARGA EL VALOR DE LA NUEVA POSICIÓN DE Z AL REGISTRO DE DECENAS DE HORA 
	STS DISP_D_HR, R16
	RET

MOSTRAR_CONTADOR_FECHA:						// ACTUALIZA DISPLAYS DE FECHA 
	// FECHA 
	LDI ZH, HIGH(tabla7<<1)					// SE REINICIA LA POSICIÓN DEL PUNTERO 
	LDI ZL, LOW(tabla7<<1)
	LDS R16, C_UNIDAD_DIA
	ADD ZL, R16								// LE SUMAMOS AL BYTE BAJO EL CONTADOR DE UNIDADES DE DÍA 
	ADC ZH, R1								// R1 SIEMPRE TIENE CERO, PERO SI LA SUMA ANTERIOR TIENE CARRY, AL BYTE ALTO DE Z, ZH, SE LE SUMA ESE CARRY 
	LPM R16, Z								// SE CARGA EL VALOR DE LA NUEVA POSICIÓN DE Z PARA EL CONTADOR DE UNIDADES DE DIA 
	STS DISP_U_DIA, R16

	LDI ZH, HIGH(tabla7<<1)					// SE REINICIA LA POSICIÓN DEL PUNTERO 
	LDI ZL, LOW(tabla7<<1)
	LDS R16, C_DECENA_DIA
	ADD ZL, R16								// LE SUMAMOS AL BYTE BAJO EL CONTADOR DE DECENAS DE DIA  
	ADC ZH, R1								// R1 SIEMPRE TIENE CERO, PERO SI LA SUMA ANTERIOR TIENE CARRY, AL BYTE ALTO DE Z, ZH, SE LE SUMA ESE CARRY 
	LPM R16, Z								// SE CARGA EL VALOR DE LA NUEVA POSICIÓN DE Z PARA EL CONTADOR DE DECENAS DE DIA 
	STS DISP_D_DIA, R16

	LDI ZH, HIGH(tabla7<<1)					// SE REINICIA LA POSICIÓN DEL PUNTERO 
	LDI ZL, LOW(tabla7<<1)
	LDS R16, C_UNIDAD_MES
	ADD ZL, R16								// LE SUMAMOS AL BYTE BAJO EL CONTADOR DE UNIDADES DE MES 
	ADC ZH, R1								// R1 SIEMPRE TIENE CERO, PERO SI LA SUMA ANTERIOR TIENE CARRY, AL BYTE ALTO DE Z, ZH, SE LE SUMA ESE CARRY 
	LPM R16, Z								// SE CARGA EL VALOR DE LA NUEVA POSICIÓN DE Z PARA EL CONTADOR DE UNIDADES DE MES 
	STS DISP_U_MES, R16

	LDI ZH, HIGH(tabla7<<1)					// SE REINICIA LA POSICIÓN DEL PUNTERO 
	LDI ZL, LOW(tabla7<<1)
	LDS R16, C_DECENA_MES
	ADD ZL, R16								// LE SUMAMOS AL BYTE BAJO EL CONTADOR DE DECENAS DE MES
	ADC ZH, R1								// R1 SIEMPRE TIENE CERO, PERO SI LA SUMA ANTERIOR TIENE CARRY, AL BYTE ALTO DE Z, ZH, SE LE SUMA ESE CARRY 
	LPM R16, Z								// SE CARGA EL VALOR DE LA NUEVA POSICIÓN DE Z AL CONTADOR DE DECENAS DE MES
	STS DISP_D_MES, R16
	RET  

CONVERTIR_A_7SEG:							// CONVIERTE UN NÚMERO (0-9) A CÓDIGO DE 7 SEGMENTOS USANDO LA TABLA
    PUSH ZH
    PUSH ZL
    PUSH R17
    LDI ZH, HIGH(tabla7<<1)
    LDI ZL, LOW(tabla7<<1)
    ADD ZL, R16
    ADC ZH, R1
    LPM R16, Z
    POP R17
    POP ZL
    POP ZH
    RET

// SUBRUTINA QUE VERIFICA SI LOS MESES Y DÍAS SELECCIONADOS POR EL USUARIO SON ´VALIDOS O NO
VERIFICAR_ESTADOS_INVALIDOS:
	LDS R16, U_DIA_ESTADO3
	LDS R17, D_DIA_ESTADO3
	LDS R18, U_MES_ESTADO3
	LDS R19, D_MES_ESTADO3 
	CPI R16, 0x0							// CASO EN EL QUE TODO ES 0 
	BRNE SALTO_A_CASO2 
	CPI R17, 0x0 
	BRNE SALTO_A_CASO2
	CPI R18, 0x0 
	BRNE SALTO_A_CASO2
	CPI R19, 0x0 
	BRNE SALTO_A_CASO2
	RJMP VERIFICACION_AUTORIZADA 
SALTO_A_CASO2:								// CASO EN EL QUE NO PUEDE EXISTIR UN MES MAYOR A 12 
	CPI R19, 0x01 
	BRNE SALTO_A_CASO3
	CPI R18, 0x03  
	BRLT SALTO_A_CASO3
	RJMP VERIFICACION_AUTORIZADA
SALTO_A_CASO3:								// CASO EN EL QUE PUEDEN EXITIR MÁS DE 31 DÍAS INDEPENDIENTEMENTE DEL MES QUE SE TENGA 
	CPI R17, 0x03 
	BRNE SALTO_A_CASO4
	CPI R16, 0x02 
	BRLT SALTO_A_CASO4 
	RJMP VERIFICACION_AUTORIZADA
SALTO_A_CASO4:								// SIN IMPORTAR EL DÍA QUE SE TENGA, NO PUEDE EXISTIR EL MES 00 
	CPI R18, 0x0 
	BRNE SALTO_A_CASO5
	CPI R19, 0x0 
	BRNE SALTO_A_CASO5
	RJMP VERIFICACION_AUTORIZADA
SALTO_A_CASO5:								// SIN IMPORTAR EL MES, NO PUEDE EXISTIR EL DÍA 00 
	CPI R16, 0x0 
	BRNE SALTO_A_CASO6
	CPI R17, 0x0
	BRNE SALTO_A_CASO6
	RJMP VERIFICACION_AUTORIZADA
SALTO_A_CASO6:								// LÍMITE PARA FEBRERO 
	CPI R18, 0x02 
	BRNE SALTO_A_CASO7
	CPI R19, 0x0 
	BRNE SALTO_A_CASO7
	CPI R16, 0x09
	BRLT SALTO_A_CASO7
	CPI R17, 0x02
	BRLT SALTO_A_CASO7
	RJMP VERIFICACION_AUTORIZADA
SALTO_A_CASO7:								// LÍMITE PARA ABRIL 
	CPI R18, 0x04 
	BRNE SALTO_A_CASO8
	CPI R19, 0x0 
	BRNE SALTO_A_CASO8
	CPI R16, 0x01
	BRLT SALTO_A_CASO8
	CPI R17, 0x03
	BRLT SALTO_A_CASO8
	RJMP VERIFICACION_AUTORIZADA
SALTO_A_CASO8:								// LÍMITE PARA JUNIO 
	CPI R18, 0x06 
	BRNE SALTO_A_CASO9
	CPI R19, 0x0 
	BRNE SALTO_A_CASO9
	CPI R16, 0x01
	BRLT SALTO_A_CASO9
	CPI R17, 0x03
	BRLT SALTO_A_CASO9
	RJMP VERIFICACION_AUTORIZADA
SALTO_A_CASO9:								// LÍMITE PARA SEPTIEMBRE 
	CPI R18, 0x09 
	BRNE SALTO_A_CASO10
	CPI R19, 0x0 
	BRNE SALTO_A_CASO10
	CPI R16, 0x01
	BRLT SALTO_A_CASO10
	CPI R17, 0x03
	BRLT SALTO_A_CASO10
	RJMP VERIFICACION_AUTORIZADA
SALTO_A_CASO10:								// LÍMITE PARA NOVIEMBRE 
	CPI R18, 0x01 
	BRNE SALIDA
	CPI R19, 0x01
	BRNE SALIDA
	CPI R16, 0x01
	BRLT SALIDA
	CPI R17, 0x03
	BRLT SALIDA
	RJMP VERIFICACION_AUTORIZADA
SALIDA:
	RJMP SALIR_VERIFICACION

// SUBRUTINA QUE SE ACTIVA SI SE CUMPLE ALGUNA CONDICIÓN DE UNA FECHA INVÁLIDA 
VERIFICACION_AUTORIZADA:
	LDI R16, 0x1
	STS U_DIA_ESTADO3, R16 
	CLR R16
	STS D_DIA_ESTADO3, R16 
	LDI R16, 0x1
	STS U_MES_ESTADO3, R16
	CLR R16
	STS D_MES_ESTADO3, R16
	CALL CAMBIAR_DISPLAY_MODO_CONFIGURACION_FECHA
SALIR_VERIFICACION:
    RET

// SUBRUTINA QUE VERIFICA SI LAS HORAS Y MINUTOS SON VÁLIDAS 
VERIFICAR_ESTADOS_INVALIDOS_E2:
	LDS R16, U_HR_ESTADO2
	LDS R17, D_HR_ESTADO2
	LDS R18, U_MIN_ESTADO2
	LDS R19, D_MIN_ESTADO2 
	CPI R16, 0x04								// CASO QUE NO SE PUEDE TENER MÁS DE 23 HORAS   
	BRLT SALTO_A_CASO2_E2 
	CPI R17, 0x02
	BRNE SALTO_A_CASO2_E2
	RJMP VERIFICACION_AUTORIZADA_E2
SALTO_A_CASO2_E2:								
	RJMP SALIR_VERIFICACION_E2

// SUBRUTINA QUE SE ACTIVA SI SE CUMPLE ALGUNA CONDICIÓN DE UNA HORA INVÁLIDA, TODO SE REINICIA A 0 
VERIFICACION_AUTORIZADA_E2:
	CLR R16 
	STS U_HR_ESTADO2, R16
	STS D_HR_ESTADO2, R16
	STS U_MIN_ESTADO2, R16
	STS D_MIN_ESTADO2, R16
	CALL CAMBIAR_DISPLAY_MODO_CONFIGURACION_HORA
SALIR_VERIFICACION_E2:
    RET
/******/
// RUTINAS DE INTERRUPCIÓN 

ISR_TIMER0:									// TIMER0 CADA 250 MS PARA CONTROLAR PARPADEO DE LED EN PC5 Y DURACIÓN DE LA ALARMA
	PUSH R16
    IN   R16,SREG
    PUSH R16

	LDS R16, CONTADOR_ALARMA				// MANEJO DE LA ALARMA: DECREMENTA CONTADOR Y APAGA BUZZER SI LLEGA A 0 			
	CPI R16, 0x0
	BREQ CONTINUA_ISR_0
	DEC R16
	STS CONTADOR_ALARMA, R16 
	CPI R16, 0x0
	BRNE CONTINUA_ISR_0 
	CBI PORTD, PORTD7						// APAGA BUZZER 
	CLR R16
	STS BUZZER_ENCENDIDO, R16 
CONTINUA_ISR_0:

	SBI TIFR0, TOV0							// PONE EN 1 LA BANDERA TOV0 PARA LIMPIAR EL OVERFLOW
	LDI R16, 0x0C
	OUT TCNT0, R16							// VUELVE A COLOCAR VALOR INICIAL AL TIMER (12)

	LDS R16, OVERFLOW_TMR0
	INC R16									// INCREMENTA EL CONTADOR DE DESBORDAMIENTOS OVERFLOW_TMR0
	STS OVERFLOW_TMR0, R16  
	CPI R16, 0x02 
	BRNE FINALIZAR_ISR0 
	CLR R16 
	STS OVERFLOW_TMR0, R16					// CADA 2 DESBORDAMIENTOS CAMBIA ESTADO DEL LED EN PC5 
	IN R16, PORTC							// SE LEE EL VALOR ACTUAL DEL PC5 PARA SABER SI EL LED ESTABA ENCENDIDO O APAGADO 
	SBRS R16, PC5
	RJMP ENCENDER_LED
	CBI PORTC, PC5							
	RJMP FINALIZAR_ISR0 
ENCENDER_LED:
	SBI PORTC, PC5
FINALIZAR_ISR0: 
	POP R16
    OUT SREG,R16
    POP R16
	RETI
	
ISR_TIMER1:									// TIMER1 CADA 60 SEGUNDOS, GENERA BANDERA INDICADOR_TMR1 PARA QUE EL PROGRAMA PRINCIPAL INCREMENTE LA HORA
	PUSH R16
    IN   R16,SREG
    PUSH R16

	SBI TIFR1, TOV1							// SE SETEA LA BANDERA DE OVERFLOW DEL TIMER 1 Y SE REESTABLECE EL VALOR DE TCNT1 
	LDI R16, 0x1B							
	STS TCNT1H, R16 
	LDI R16, 0x1F							
	STS TCNT1L, R16 
					
	LDI R16, 0x1
	STS INDICADOR_TMR1, R16					// SE LE CARGA A LA VARIABLE INDICADOR_TMR1 UN 1 PARA QUE EN EL LOOP PRINCIPAL SE SEPA SI YA PASÓ UN MINUTO 
	
FINAL_RETI1:
	POP R16
    OUT SREG,R16
    POP R16
	RETI

ISR_TIMER2:									// TIMER2 CADA 2MS (MULTIPLEXADO DE DISPLAYS), BARRE LOS 4 DÍGITOS, ENCENDIENDO UNO A LA VEZ Y MOSTRANDO EL VALOR CORRESPONDIENTE
	PUSH R16								// SEGÚN MODO_DISPLAY, ADEMÁS PRESERVA EL ESTADO DEL BUZZER (BIT 7 DE PORTD)
    IN   R16,SREG
    PUSH R16
	PUSH R17 

	CBI PORTB, PB0							// SE APAGAN TODOS LOS TRANSISTORES
	CBI PORTB, PB1
	CBI PORTB, PB2
	CBI PORTB, PB3
	SBI TIFR2, TOV2							// SE REINICIA BANDERA DE OVERFLOW PARA TIMER 2 Y SE REESTABLECE TCNT2
	LDI R16, 0x06 
	STS TCNT2, R16
	LDS R16, DISP_SELEC
	INC R16									// SE SUMA LA VARIABLE DE DISP_SELEC QUE SIRVE COMO ÍNDICE PARA SABER QUE DISPLAY SE TIENE QUE ENCENDER
	STS DISP_SELEC, R16 
	CPI R16, 0x04							// SOLO HAY 4 DISPLAYS Y SE CUENTA DE 0 A 3, DE LLEGAR A 4 SE REINICIA LA CUENTA DEL ÍNDICE 
	BRNE MULTIPLEX_ISR
	CLR R16
	STS DISP_SELEC, R16

MULTIPLEX_ISR:
	CPI R16, 0x0							// SE COMPARA LA VARIABLE DE DISP_SELEC CON LOS VALORES DEL ÍNDICE DETERMINADOS PARA CADA DISPLAY
	BREQ DIGITO_1			
	CPI R16, 0x1							// SI LA VARIABLE DISP_SELEC ES IGUAL A 2, SE ENCIENDE EL DISPLAY DEL DÍGITO 2
	BREQ DIGITO_2	
	CPI R16, 0x2 
	BREQ SALTO_DIGITO3  
	RJMP DIGITO_4 
SALTO_DIGITO3: 
	RJMP DIGITO_3 
DIGITO_1:
	SBI PORTB, PB0							// SE ENCIENDE EL TRANSISTOR DEL DÍGITO 1
	LDS R17, MODO_DISPLAY 
	CPI R17, 0x0 
	BRNE DIGITO1_DETECCION_ESTADO1
	LDS R16, DISP_U_MIN						// MODO HORA: UNIDAD DE MINUTO 
	ANDI R16, 0b01111111					// ASEGURA BIT DE BUZZER EN 0 
	IN R17, PORTD
	ANDI R17, 0b10000000					// CONSERVA ESTADO DEL BUZZER 
	OR R16, R17
	OUT PORTD, R16							// SE SACA EL VALOR DE LAS UNIDADES DE MINUTO 
	RJMP FINAL_RETI

DIGITO1_DETECCION_ESTADO1:
	CPI R17, 0x01 
	BRNE DIGITO1_DETECCION_ESTADO2
	LDS R16, DISP_U_MES						// MODO FECHA: UNIDAD DE MES 
	ANDI R16, 0b01111111
	IN R17, PORTD
	ANDI R17, 0b10000000
	OR R16, R17
	OUT PORTD, R16							// SE SACA EL VALOR DE LAS UNIDADES DE MES 
	RJMP FINAL_RETI

DIGITO1_DETECCION_ESTADO2:
	CPI R17, 0x02 
	BRNE DIGITO1_DETECCION_ESTADO3
	LDS R16, DISP_ESTADO2_1					// MODO CONFIGURACIÓN HORA: DISPLAY DÍGITO 1
	ANDI R16, 0b01111111
	IN R17, PORTD
	ANDI R17, 0b10000000
	OR R16, R17
	OUT PORTD, R16							
	RJMP FINAL_RETI

DIGITO1_DETECCION_ESTADO3:
	CPI R17, 0x03 
	BRNE SALTO_FINAL_RETI
	LDS R16, DISP_ESTADO3_1					// MODO CONFIGURACIÓN DE FECHA: DISPLAY DÍGITO 1 
	ANDI R16, 0b01111111
	IN R17, PORTD
	ANDI R17, 0b10000000
	OR R16, R17
	OUT PORTD, R16						
	RJMP FINAL_RETI
SALTO_FINAL_RETI:
	RJMP FINAL_RETI
DIGITO_2:
	SBI PORTB, PB1							// SE ENCIENDE EL TRANSISTOR DEL DÍGITO 2 
	LDS R17, MODO_DISPLAY 
	CPI R17, 0x0 
	BRNE DIGITO2_DETECCION_ESTADO1
	LDS R16, DISP_D_MIN						// MODO HORA: DECENA DE MINUTO 
	ANDI R16, 0b01111111
	IN R17, PORTD
	ANDI R17, 0b10000000
	OR R16, R17
	OUT PORTD, R16							
	RJMP FINAL_RETI

DIGITO2_DETECCION_ESTADO1:
	CPI R17, 0x01 
	BRNE DIGITO2_DETECCION_ESTADO2
	LDS R16, DISP_D_MES						// MODO FECHA: DECENA DE MES 
	ANDI R16, 0b01111111
	IN R17, PORTD
	ANDI R17, 0b10000000
	OR R16, R17
	OUT PORTD, R16							 
	RJMP FINAL_RETI

DIGITO2_DETECCION_ESTADO2:
	CPI R17, 0x02 
	BRNE DIGITO2_DETECCION_ESTADO3
	LDS R16, DISP_ESTADO2_2					// MODO CONFIGURACIÓN DE HORA: DISPAY DÍGITO 2 
	ANDI R16, 0b01111111
	IN R17, PORTD
	ANDI R17, 0b10000000
	OR R16, R17
	OUT PORTD, R16							
	RJMP FINAL_RETI

DIGITO2_DETECCION_ESTADO3:
	CPI R17, 0x03 
	BREQ CONTINUA_DIGITO2_DETECCION_ESTADO3
	RJMP FINAL_RETI
CONTINUA_DIGITO2_DETECCION_ESTADO3:
	LDS R16, DISP_ESTADO3_2					// MODO CONFIGURACIÓN DE FECHA: DISPLAY DE DÍGITO 2
	ANDI R16, 0b01111111
	IN R17, PORTD
	ANDI R17, 0b10000000
	OR R16, R17
	OUT PORTD, R16							 
	RJMP FINAL_RETI

DIGITO_3:
	SBI PORTB, PB2							// SE ENCIENDE EL TRANSISTOR DEL DÍGITO 3
	LDS R17, MODO_DISPLAY 
	CPI R17, 0x0 
	BRNE DIGITO3_DETECCION_ESTADO1
	LDS R16, DISP_U_HR						// MODO HORA: UNIDAD DE HORA 
	ANDI R16, 0b01111111
	IN R17, PORTD
	ANDI R17, 0b10000000
	OR R16, R17
	OUT PORTD, R16							
	RJMP FINAL_RETI

DIGITO3_DETECCION_ESTADO1:
	CPI R17, 0x01 
	BRNE DIGITO3_DETECCION_ESTADO2
	LDS R16, DISP_U_DIA						// MODO FECHA: UNIDAD DE DÍA 
	ANDI R16, 0b01111111
	IN R17, PORTD
	ANDI R17, 0b10000000
	OR R16, R17
	OUT PORTD, R16							
	RJMP FINAL_RETI

DIGITO3_DETECCION_ESTADO2:
	CPI R17, 0x02 
	BRNE DIGITO3_DETECCION_ESTADO3
	LDS R16, DISP_ESTADO2_3					// MODO CONFIGURACIÓN DE HORA: DISPLAY DÍGITO 3 
	ANDI R16, 0b01111111
	IN R17, PORTD
	ANDI R17, 0b10000000
	OR R16, R17
	OUT PORTD, R16							 
	RJMP FINAL_RETI

DIGITO3_DETECCION_ESTADO3:
	CPI R17, 0x03 
	BRNE FINAL_RETI
	LDS R16, DISP_ESTADO3_3					// MODO CONFIGURACIÓN DE FECHA: DISPLAY DÍGITO 3
	ANDI R16, 0b01111111
	IN R17, PORTD
	ANDI R17, 0b10000000
	OR R16, R17
	OUT PORTD, R16							
	RJMP FINAL_RETI

DIGITO_4:
	SBI PORTB, PB3							// SE ENCIENDE EL TRANSISTOR DEL DÍGITO 4
	LDS R17, MODO_DISPLAY 
	CPI R17, 0x0 
	BRNE DIGITO4_DETECCION_ESTADO1
	LDS R16, DISP_D_HR						// MODO HORA: DECENA DE HORA 
	ANDI R16, 0b01111111
	IN R17, PORTD
	ANDI R17, 0b10000000
	OR R16, R17
	OUT PORTD, R16							  
	RJMP FINAL_RETI

DIGITO4_DETECCION_ESTADO1:
	CPI R17, 0x01 
	BRNE DIGITO4_DETECCION_ESTADO2
	LDS R16, DISP_D_DIA						// MODO FECHA: DECENA DE DÍA 
	ANDI R16, 0b01111111
	IN R17, PORTD
	ANDI R17, 0b10000000
	OR R16, R17
	OUT PORTD, R16							
	RJMP FINAL_RETI

DIGITO4_DETECCION_ESTADO2:
	CPI R17, 0x02 
	BRNE DIGITO4_DETECCION_ESTADO3
	LDS R16, DISP_ESTADO2_4					// MODO CONFIGURACIÓN DE HORA: DISPLAY DÍGITO 4
	ANDI R16, 0b01111111
	IN R17, PORTD
	ANDI R17, 0b10000000
	OR R16, R17
	OUT PORTD, R16							
	RJMP FINAL_RETI

DIGITO4_DETECCION_ESTADO3:
	CPI R17, 0x03 
	BRNE FINAL_RETI
	LDS R16, DISP_ESTADO3_4					// MODO CONFIGURACIÓN DE FECHA: DÍGITO 4
	ANDI R16, 0b01111111
	IN R17, PORTD
	ANDI R17, 0b10000000
	OR R16, R17
	OUT PORTD, R16							
	RJMP FINAL_RETI

FINAL_RETI:
	POP R17
	POP R16
    OUT SREG,R16
    POP R16
	RETI 

PINC_ISR:									// INTERRUPCIÓN POR CAMBIO EN PINC (BOTONES) DETECTA FLANCOS DE BAJADA EN LOS PINES PC0PC4 Y ACTIVA LAS RESPECTIVAS BANDERAS
	PUSH R16
    IN   R16,SREG
    PUSH R16
	PUSH R17 
	PUSH R18 

	IN R16, PINC							
	ANDI R16, 0b0001_1111					// SOLO SE QUEDAN LOS PINES DE LOS BOTONES 
	LDS R17, PINC_ANTERIOR					// SE GUARDA COMO ESTABAN LOS BOTONES ANTES
	STS PINC_ANTERIOR, R16					// SE GUARDA EL ESTADO ACTUAL PARA LA PRÓXIMA OCASIÓN 
	LDI R18, 0b0001_1111					// MÁSCARA PARA BOTONES 
	EOR R18, R16							// XOR ENTRE LA MÁSCARA Y EL ESTADO ANTERIOR DE LOS BOTONES PARA ENCENDER LOS QUE ESTABAN EN 0 (PRESIONADOS POR PULLUP)
	AND R18, R17							// DEJA EN 1 LOS BOTONES QUE ESTABAN PRESIONADOS ANTES 

	MOV R16, R18 
	ANDI R16, 0b0000_0001					// MÁSCARA PARA SOLO LEER UN BOTÓN A LA VEZ
	CPI R16, 0b0000_0001					// COMPARACIÓN PARA DEJAR PASAR 
	BRNE CONTINUA_BOTON2					// DE SER DIFERENTE CONTINUA CON EL SIGUIENTE BOTÓN 
	LDI R16, 0x01							// DE SER IGUAL LA COMPARACIÓN, SE LE CARGA 1 A MODO DE BANDERA A LA VARIABLE INDICADOR_BOTÓN1 
	STS INDICADOR_BOTON1, R16

CONTINUA_BOTON2:
	MOV R16, R18 
	ANDI R16, 0b0000_0010					// MÁSCARA PARA SOLO LEER UN BOTÓN A LA VEZ
	CPI R16, 0b0000_0010					// COMPARACIÓN PARA DEJAR PASAR
	BRNE CONTINUA_BOTON3					// DE SER DIFERENTE CONTINUA CON EL SIGUIENTE BOTÓN 
	LDI R16, 0x01							// DE SER IGUAL LA COMPARACIÓN, SE LE CARGA 1 A MODO DE BANDERA A LA VARIABLE INDICADOR_BOTÓN2 
	STS INDICADOR_BOTON2, R16

CONTINUA_BOTON3:
	MOV R16, R18 
	ANDI R16, 0b0000_0100					// MÁSCARA PARA SOLO LEER UN BOTÓN A LA VEZ
	CPI R16, 0b0000_0100					// COMPARACIÓN PARA DEJAR PASAR
	BRNE CONTINUA_BOTON4					// DE SER DIFERENTE CONTINUA CON EL SIGUIENTE BOTÓN 
	LDI R16, 0x01							// DE SER IGUAL LA COMPARACIÓN, SE LE CARGA 1 A MODO DE BANDERA A LA VARIABLE INDICADOR_BOTÓN3
	STS INDICADOR_BOTON3, R16

CONTINUA_BOTON4:
	MOV R16, R18 
	ANDI R16, 0b0000_1000					// MÁSCARA PARA SOLO LEER UN BOTÓN A LA VEZ
	CPI R16, 0b0000_1000					// COMPARACIÓN PARA DEJAR PASAR
	BRNE CONTINUA_BOTON5					// DE SER DIFERENTE CONTINUA CON EL SIGUIENTE BOTÓN 
	LDI R16, 0x01							// DE SER IGUAL LA COMPARACIÓN, SE LE CARGA 1 A MODO DE BANDERA A LA VARIABLE INDICADOR_BOTÓN4 
	STS INDICADOR_BOTON4, R16

CONTINUA_BOTON5:
	MOV R16, R18 
	ANDI R16, 0b0001_0000					// MÁSCARA PARA SOLO LEER UN BOTÓN A LA VEZ
	CPI R16, 0b0001_0000					// COMPARACIÓN PARA DEJAR PASAR
	BRNE FINAL_ISR_PINC						// DE SER DIFERENTE CONTINUA CON EL SIGUIENTE BOTÓN 
	LDI R16, 0x01							// DE SER IGUAL LA COMPARACIÓN, SE LE CARGA 1 A MODO DE BANDERA A LA VARIABLE INDICADOR_BOTÓN5
	STS INDICADOR_BOTON5, R16

FINAL_ISR_PINC:
	POP R18 
	POP R17
	POP R16
    OUT SREG,R16
    POP R16
	RETI 
/******/