/*
* NombreProgra.asm
*
* Creado: 24/02/2026
* Autor : Omar Cabrera 24571
* Descripción: Interrupciones para: Contador binario de 4 bits, contador hexadecimal y contador de decenas. 
*/
/******/
// Encabezado (Definición de Registros, Variables y Constantes)
.include "M328PDEF.inc"     // Include definitions specific to ATMega328P
.dseg
.org    SRAM_START
//variable_name:     .byte   1   // Memory alocation for variable_name:     .byte   (byte size)

.cseg
.org 0x0000						// EMPIEZA A PROGRAMAR EN 0 
	JMP START
.org PCI1addr					// NOMBRE RESERVADO PARA LA DIRECCIÓN 0x0008 ; HABILITA INTERRUPCIONES PARA PUERTO C
	JMP ISR_PCINT1

.org OVF0addr					// NOMBRE RESERVADO PARA LA DIRECCIÓN 0x0020 ; HABILITA INTERRUPCIONES PARA TIMER0 
	JMP ISR_TIMER0   

 /******/
// Configuración de la pila

START:
LDI     R16, LOW(RAMEND)
OUT     SPL, R16
LDI     R16, HIGH(RAMEND)
OUT     SPH, R16

// TABLA QUE CONTIENE TODOS LOS DATOS A DESPLEGAR PARA EL DISPLAY 

tabla7: .DB 0xC0, 0xF9, 0xA4, 0xB0, 0x99, 0x92, 0x82, 0xB8, 0x80, 0x98, 0x88, 0x83, 0xC6, 0xA1, 0x86, 0x8E

/******/
// Configuracion MCU
SETUP:
	CLI										// DESHABILITAMOS INTERRUPCIONES  

	// SETTING PRESCALER A 1MHZ 
	LDI R16, (1<<CLKPCE)
	STS CLKPR, R16						
	LDI R16, 0b0000_0100
	STS CLKPR, R16

	// CONFIGURACIÓN DEL TIMER0
	LDI R16, 0x0
	OUT TCCR0A, R16						// CONFIGURAR EL MODO DEL RELOJ, EN ESTE CASO MODO NORMAL 
	LDI R16, 0b0000_0100				
	OUT TCCR0B, R16						// CONFIGURAR EL PRESCALER A 256
	LDI R16, 0xB2						
	OUT TCNT0, R16						// CARGAR EL VALOR INICIAL DEL CONTADOR, EL VALOR CALCULADO FUE DE 178

	// PUNTERO Z PARA ESTABLECER EL HIGH Y LOW DE NUESTRO "DICCIONARIO"
	LDI ZH, HIGH(tabla7<<1)
	LDI ZL, LOW(tabla7<<1)
	
	// CONFIGURACIÓN DE ENTRADAS Y SALIDAS 

	// CONFIGURACIÓN DE SALIDAS PARA LOS LEDS EN EL PUERTO D, INICIALMENTE APAGADOS
	LDI R16, 0b1111_1111
	OUT DDRD, R16 
	LDI R16, 0b0000_0000 
	OUT PORTD, R16

	// DESACTIVAR UART (PARA QUE NO HAYAN PROBLEMAS CON TX y RX)
	LDI R16, 0x00
	STS UCSR0B, R16

	// CONFIGURACIÓN DE TIMER0 
	
	LDI R16, (1<< TOIE0)					// ACTIVO INTERRUPCIONES PARA EL TIMER EN MODO NORMAL  
	STS TIMSK0, R16				 

	// CONFIGURACIÓN ENTRADAS DE BOTONES Y SALIDAS DE CONTROL PARA TRANSISTORES

	CBI DDRC, DDC0							// PC0 COMO ENTRADA PULLUP PARA BOTÓN INCREMENTO  
	SBI PORTC, PORTC0 

	CBI DDRC, DDC1							// PC1 COMO ENTRADA PULLUP PARA BOTÓN DECREMENTO 
	SBI PORTC, PORTC1		

	LDI R16, 0b0000_1111					// LEDS COMO SALIDAS EN EL PUERTOB 
	OUT DDRB, R16 
	LDI R16, 0x0							
	OUT PORTB, R16 

	SBI DDRC, DDC2							// SALIDAS PARA CONTROLAR TRANSISTORES 
	CBI PORTC, PC2							// PC2 PARA LAS UNIDADES 
	SBI DDRC, DDC3							// PC3 PARA LAS DECENAS
	CBI PORTC, PC3 

	// CONFIGURACIÓN DE PCINT1 
	
	LDI R16, (1<< PCIE1)					// ACTIVO INTERRUPCIONES AL PUERTO C 
	STS PCICR, R16 

	LDI R16, (1<< PCINT8)|(1<<PCINT9)		// ACTIVO INTERRUPCIONES SOLO PARA LOS PINES PC0 Y PC1 
	STS PCMSK1, R16 

	// INICIALIZACIÓN DE VARIABLES 
	CLR R1
	CLR R18									// REGISTRO BANDERA/INDICADOR DE QUE BOTÓN FUE PRESIONADO
	CLR R19									// PARA DELAY 
	CLR R21									// CONTADOR DE 4 BITS 
	CLR R22									// CONTADOR PARA EL DISPLAY DE UNIDADES
	CLR R23									// CONTADOR PARA EL DISPLAY DE DECENAS
	CLR R24									// CONTADOR DE DESBORDAMIENTOS PARA EL TIMER0 
	CLR R25									// REGISTRO QUE CONTIENE LA POSICIÓN ACTUAL DE Z PARA UNIDADES
	CLR R26									// REGUSTRO QUE CONTIENE LA POSICIÓN ACTUAL DE Z PARA DECENAS  

	SEI


/******/
// Loop Infinito
MAIN_LOOP:

	RCALL MULTIPLEX

// CONTADOR 
	CPI R24, 0x32							// COMPARA EL R24 CON 50, SI NO ES 50 REPITE HASTA QUE LO SEA 
	BRNE MAIN_LOOP 
	CLR R24									// SE LIMPIA EL CONTADOR DE DESBORDAMIENTOS 
	INC R22									// SE SUMA EL CONTADOR HEXADECIMAL 
	CPI R22, 0xA							// COMPARO CON 10 (A) PARA SABER SI YA CONTÓ 10 SEGUNDOS, DE SER DIFERENTE SALTA A LA RUTINA MOSTRAR CONTADOR 
	BRNE MOSTRAR_CONTADOR_UNIDADES
	CLR R22									// DE SER EL REGISTRO DE UNIDADES IGUAL A 10, SIGNIFICA QUE YA CONTÓ 10 SEGUNDOS  
	INC R23									// AUMENTA EL CONTADOR DE DECENAS 
	// ACTUALIZAR CONTADORES PARA R25 Y R26
	LDI ZH, HIGH(tabla7<<1)					// SE REINICIA LA POSICIÓN DEL PUNTERO 
	LDI ZL, LOW(tabla7<<1)
	ADD ZL, R22								// LE SUMAMOS AL BYTE BAJO EL CONTADOR DE UNIDADES 
	ADC ZH, R1								// R1 SIEMPRE TIENE CERO, PERO SI LA SUMA ANTERIOR TIENE CARRY, AL BYTE ALTO DE Z, ZH, SE LE SUMA ESE CARRY 
	LPM R25, Z								// SE CARGA EL VALOR DE LA NUEVA POSICIÓN DE Z AL REGISTRO R25 DE UNIDADES 

	LDI ZH, HIGH(tabla7<<1)					// SE REINICIA LA POSICIÓN DEL PUNTERO 
	LDI ZL, LOW(tabla7<<1)
	ADD ZL, R23								// LE SUMAMOS AL BYTE BAJO EL CONTADOR DE DECENAS 
	ADC ZH, R1								// R1 SIEMPRE TIENE CERO, PERO SI LA SUMA ANTERIOR TIENE CARRY, AL BYTE ALTO DE Z, ZH, SE LE SUMA ESE CARRY 
	LPM R26, Z								// SE CARGA EL VALOR DE LA NUEVA POSICIÓN DE Z AL REGISTRO R26 DE DECENAS 


	CPI R23, 0x6							// COMPARO EL CONTADOR DE DECENAS CON 6, PARA SABER SI YA SE CONTARON 60 SEGUNDOS
	BRNE MOSTRAR_CONTADOR_DECENAS
	CLR R23									// DE SER EL REGISTRO DE DECENAS IGUAL A 6, REINICIAMOS EL CONTADOR, LLEGO A LOS 60 SEGUNDOS
	CLR R22									// CUANDO SE LLEGUÉ A LOS 60 SEGUNDOS, TAMBÉN SE REINICIA EL CONTADOR DE UNIDADES 
	LDI ZH, HIGH(tabla7<<1)					// SE REINICIA LA POSICIÓN DEL PUNTERO 
	LDI ZL, LOW(tabla7<<1)
	ADD ZL, R22								// LE SUMAMOS AL BYTE BAJO EL CONTADOR DE UNIDADES 
	ADC ZH, R1								// R1 SIEMPRE TIENE CERO, PERO SI LA SUMA ANTERIOR TIENE CARRY, AL BYTE ALTO DE Z, ZH, SE LE SUMA ESE CARRY 
	LPM R25, Z								// SE CARGA EL VALOR DE LA NUEVA POSICIÓN DE Z AL REGISTRO R25 DE UNIDADES 

	LDI ZH, HIGH(tabla7<<1)					// SE REINICIA LA POSICIÓN DEL PUNTERO 
	LDI ZL, LOW(tabla7<<1)
	ADD ZL, R23								// LE SUMAMOS AL BYTE BAJO EL CONTADOR DE DECENAS 
	ADC ZH, R1								// R1 SIEMPRE TIENE CERO, PERO SI LA SUMA ANTERIOR TIENE CARRY, AL BYTE ALTO DE Z, ZH, SE LE SUMA ESE CARRY 
	LPM R26, Z								// SE CARGA EL VALOR DE LA NUEVA POSICIÓN DE Z AL REGISTRO R26 DE DECENAS 
	

// BOTONES 
	SBRS R18, 0									
	RJMP CHEQUEO_DECREMENTO
	RJMP INCREMENTAR_CONTADOR
	
CHEQUEO_DECREMENTO:
	SBRS R18, 1												
	RJMP MAIN_LOOP
    RJMP DECREMENTAR_CONTADOR

/******/
// NON-Interrupt subroutines

MULTIPLEX: 
	SBI PORTC, PC2							// ENCIENDO TRANSISTOR EN PC2 QUE PERMITE VER LAS UNIDADES 
	CBI PORTC, PC3
	OUT PORTD, R25
	CALL DELAY 
	CBI PORTC, PC2							// ENCIENDO TRANSISTOR EN PC3 QUE PERMITE VER LAS DECENAS 
	SBI PORTC, PC3 
	OUT PORTD, R26
	CALL DELAY 
	RET 

DELAY: 
	LDI R19, 0x0 
BUCLE1:
	INC R19 
	CPI R19, 0x0 
	BRNE BUCLE1
	RET 
	

MOSTRAR_CONTADOR_UNIDADES:
	LDI ZH, HIGH(tabla7<<1)				// REINICIAMOS POSICIÓN DEL PUNTERO 
	LDI ZL, LOW(tabla7<<1)
	ADD ZL, R22							// LE SUMAMOS AL BYTE BAJO EL CONTADOR 
	ADC ZH, R1							// R1 SIEMPRE TIENE CERO, PERO SI LA SUMA ANTERIOR TIENE CARRY, AL BYTE ALTO DE Z, ZH, SE LE SUMA ESE CARRY 
	LPM R25, Z							// SE CARGA EL VALOR DE LA NUEVA POSICIÓN DE Z AL REGISTRO 25
	RJMP MAIN_LOOP

MOSTRAR_CONTADOR_DECENAS:
	LDI ZH, HIGH(tabla7<<1)				// REINICIAMOS POSICIÓN DEL PUNTERO 
	LDI ZL, LOW(tabla7<<1)
	ADD ZL, R23							// LE SUMAMOS AL BYTE BAJO EL CONTADOR 
	ADC ZH, R1							// R1 SIEMPRE TIENE CERO, PERO SI LA SUMA ANTERIOR TIENE CARRY, AL BYTE ALTO DE Z, ZH, SE LE SUMA ESE CARRY 
	LPM R26, Z							// SE CARGA EL VALOR DE LA NUEVA POSICIÓN DE Z AL REGISTRO 25
	RJMP MAIN_LOOP

// LÓGICA PARA INCREMENTAR EL CONTADOR  

INCREMENTAR_CONTADOR:
	CBR R18, (1<<0)								// LIMPIO EL BIT0 DEL REGISTRO 18 QUE CORRESPONDE AL BOTÓN INCREMENTO
	INC R21 
	CPI R21, 0x10								// COMPARAR CON 16 PARA SABER SI LLEGO A OVERFLOW 
	BREQ OVERFLOW_CONTADOR						// LLAMAMOS A LA FUNCIÓN OVERFLOW
	OUT PORTB, R21								// DE NO HABER OVERLFOW MOSTRAMOS VALOR DEL CONTADOR EN LAS LEDS
	RJMP MAIN_LOOP 
	
OVERFLOW_CONTADOR:								// DE HABER OVERFLOW, SE LIMPIA EL CONTADOR, SE MUESTRA Y REGRESA A LOOP PRINCIPAL
	CLR R21
	OUT PORTB, R21
	RJMP MAIN_LOOP

// LÓGICA PARA DECREMENTAR EL CONTADOR
	
DECREMENTAR_CONTADOR:
	CBR R18, (1<<1)								// LIMPIO EL BIT1 DEL REGISTRO 18 QUE CORRESPONDE AL BOTÓN DECREMENTO
	DEC R21 
	CPI R21, 0xFF								// COMPARAR CON 255 PARA SABER SI LLEGO A UNDERFLOW 
	BREQ UNDERFLOW_CONTADOR						// LLAMAMOS A LA FUNCIÓN UNDERFLOW
	OUT PORTB, R21								// DE NO HABER UNDERFLOW MOSTRAMOS VALOR DEL CONTADOR EN LAS LEDS
	RJMP MAIN_LOOP

UNDERFLOW_CONTADOR:
	LDI R21, 0xF								// CARGAR A CONTADOR EL VALOR DECIMAL 15 
	OUT PORTB, R21 
	RJMP MAIN_LOOP

/******/
// Interrupt routines

ISR_PCINT1: 
	SBIS PINC, PC0							// LECTURA DE PC0 (BOTÓN INCREMENTO) 
	SBR R18, (1<<0)							//	USO R18 COMO INDICADOR DE QUE BOTÓN FUE PRESIONADO (COLOCO 1 AL BIT0)
	SBIS PINC, PC1							// LECTURA DE PC1 (BOTÓN DE DECREMENTO)
	SBR R18, (1<<1)							// USO R18 COMO INDICADOR DE QUE BOTÓN FUE PRESIONADO (COLOCO 1 AL BIT1)
	RETI

ISR_TIMER0:
	INC R24									// INCREMENTA EL CONTADOR DE DESBORDAMIENTOS 
	SBI TIFR0, TOV0							// PONE EN 1 LA BANDERA TOV0 PARA LIMPIAR EL OVERFLOW
	LDI R16, 0xB2
	OUT TCNT0, R16							// VUELVE A COLOCAR VALOR INICIAL AL TIMER
	RETI 


/******/
